In [2]:
import pandas as pd
sheets = pd.read_excel("./datasets/Scats Data October 2006.xls", sheet_name=None)
sheets.keys()

dict_keys(['Notes', 'Data', 'Summary Of Data'])

What does the notes have to say?

In [3]:
sheets["Notes"]["Unnamed: 1"].dropna().to_list()

['Request: ',
 'Attached is the 24 hour volume for 40 SCATS sites collected in Boroondara Council',
 'Collection Period: 1st October 2006 to 31st October 2006 (1st October - last Sunday of School holidays)',
 'Data is available every 15minutes for each day collected. Data was validated as per ISD standards for all sites.',
 'On selected days the Data for the following sites was very poor and was removed: ',
 970,
 2000,
 2820,
 3001,
 3002,
 3127,
 3682,
 3685,
 4057,
 4262,
 4263,
 4264,
 4272,
 4812]

In [4]:
removed_days = sheets["Notes"]["Unnamed: 1"].dropna().to_list()[5:]
removed_days = [int(i) for i in removed_days]
removed_days

[970,
 2000,
 2820,
 3001,
 3002,
 3127,
 3682,
 3685,
 4057,
 4262,
 4263,
 4264,
 4272,
 4812]

In [5]:
df_info = sheets["Summary Of Data"].loc[2:]
df_info.columns = df_info.iloc[0]
df_info = df_info[1:]
df_info["SCATS Number"] = df_info["SCATS Number"].ffill()

df_info.dropna(axis=1, inplace=True)
df_info = df_info.convert_dtypes().infer_objects()
df_info.head(15)

2  SCATS Number                         Location  Total
3          0970  HIGH STREET_RD E of WARRIGAL_RD     31
4          0970  HIGH STREET_RD W of WARRIGAL_RD     30
5          0970  WARRIGAL_RD N of HIGH STREET_RD     31
6          0970  WARRIGAL_RD S of HIGH STREET_RD     31
7          2000     BURWOOD_HWY E of WARRIGAL_RD     29
8          2000       TOORAK_RD W of WARRIGAL_RD     29
9          2000       WARRIGAL_RD N of TOORAK_RD     28
10         2000     WARRIGAL_RD S of BURWOOD_HWY     28
11         2200      MAROONDAH_HWY E of UNION_RD     31
12         2200      MAROONDAH_HWY W of UNION_RD     31
13         2200      UNION_RD N of MAROONDAH_HWY     31
14         2200      UNION_RD S of MAROONDAH_HWY     31
15         2820        EARL_ST SE of PRINCESS_ST     31
16         2820    PRINCESS_ST S of CHANDLER_HWY     30
17         2825        BURKE_RD S of EASTERN_FWY     31

Threshold of Days

In [6]:
df_info_filtered = df_info[df_info["Total"].between(7, 31)]
df_info_filtered

2   SCATS Number                         Location  Total
3           0970  HIGH STREET_RD E of WARRIGAL_RD     31
4           0970  HIGH STREET_RD W of WARRIGAL_RD     30
5           0970  WARRIGAL_RD N of HIGH STREET_RD     31
6           0970  WARRIGAL_RD S of HIGH STREET_RD     31
7           2000     BURWOOD_HWY E of WARRIGAL_RD     29
..           ...                              ...    ...
137         4812          SWAN_ST SW of MADDEN_GV     26
138         4821      BURNLEY_ST S OF VICTORIA_ST     31
139         4821      VICTORIA_ST E OF BURNLEY_ST     31
140         4821      VICTORIA_ST W OF BURNLEY_ST     31
141         4821       WALMER_ST N OF VICTORIA_ST     31

[137 rows x 3 columns]

so these are locations with actually reasonable values, so we can filter out the rest of the shitfuckery

In [7]:

# imagine having good formatting
df = sheets["Data"]
df.columns = pd.Series(df.loc[0])
df = df.loc[1:]

# remove added time
df.loc[:, 'Date'] = pd.to_datetime(df['Date']).dt.date
df = df.convert_dtypes()

# filter good locations
df = df.loc[df["Location"].isin(df_info_filtered["Location"])]

# add location identifier: SCARS Number + VicRoads Internal
df.loc[:, "Identifier"] = df["SCATS Number"].astype(str) + " - " + df["HF VicRoads Internal"].astype(str)
df.columns = df.columns.str.strip()


df.head(10)

,SCATS Number,Location,CD_MELWAY,NB_LATITUDE,NB_LONGITUDE,HF VicRoads Internal,VR Internal Stat,VR Internal Loc,NB_TYPE_SURVEY,Date,...,V87,V88,V89,V90,V91,V92,V93,V94,V95,Identifier
1,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-01,...,97,97,66,81,50,59,47,29,34,0970 - 249
2,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-02,...,102,107,114,80,60,62,48,44,26,0970 - 249
3,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-03,...,132,114,86,93,90,73,57,29,40,0970 - 249
4,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-04,...,113,132,101,113,90,78,66,52,44,0970 - 249
5,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-05,...,120,116,113,99,91,61,55,49,36,0970 - 249
6,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-06,...,137,135,136,108,120,115,102,74,78,0970 - 249
7,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-07,...,153,133,109,140,121,123,115,107,127,0970 - 249
8,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-08,...,92,96,82,80,64,64,48,48,43,0970 - 249
9,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-09,...,107,111,98,83,69,57,50,25,36,0970 - 249
10,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-10,...,131,124,111,112,103,66,50,49,36,0970 - 249

In [8]:
pd.Categorical(df["NB_TYPE_SURVEY"])

[1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1]
Length: 4128
Categories (1, Int64): [1]

In [9]:
test_unique_cols = ["SCATS Number","HF VicRoads Internal","VR Internal Stat","VR Internal Loc","Location"]

for col in test_unique_cols:
    print(pd.Categorical(df.groupby("Identifier")[col].nunique()))

[1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1]
Length: 137
Categories (1, int64): [1]
[1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1]
Length: 137
Categories (1, int64): [1]
[1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1]
Length: 137
Categories (1, int64): [1]
[1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1]
Length: 137
Categories (1, int64): [1]
[1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1]
Length: 137
Categories (1, int64): [1]

Using Identifiers to identify groups. Now, we need to drop irrelevant group info:

- SCATS Number, VicRoads Internal (included in identifier)
- Location (can be accessible via identifier later)
- Latitude and Longtitude (accessible via Location) (wait keeping this is better)
- VR Internal Stat,VR Internal Loc,NB_TYPE_SURVEY (what even are these?)

In [10]:
groups = df.groupby(by="Identifier")
for name, group in groups:
    # print("Name:", name)
    # print("Info:", group.info())
    gr = group.copy()
    gr = gr.drop(columns=["SCATS Number", "HF VicRoads Internal", "Location", "VR Internal Stat", "VR Internal Loc", "NB_TYPE_SURVEY", "CD_MELWAY"])
    gr.reset_index(drop=True, inplace=True)
    print(gr.head(5))
    gr.to_csv(f"datasets/boroondara/{name}.csv")
    print(f"Saved Group {name} to boroondara/{name}.csv")

0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0     -37.8676     145.09146  2006-10-01   92   93   90   55   64   50   47
1     -37.8676     145.09146  2006-10-02   31   19   20   20   12    8   12
2     -37.8676     145.09146  2006-10-03   20   29   16    9    8   13    8
3     -37.8676     145.09146  2006-10-04   32   30   26   13   22   17   13
4     -37.8676     145.09146  2006-10-05   42   37   19   18   12   20   23

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...  117   87   82   55   58   57   51   41   41  0970 - 10503
1  ...  107  107   88   66   54   68   58   49   29  0970 - 10503
2  ...  144  100  100  102   86   85   68   53   37  0970 - 10503
3  ...  114  131   94   84   82   90   76   50   45  0970 - 10503
4  ...  158  127  118   92  105  113   78   64   62  0970 - 10503

[5 rows x 100 columns]
Saved Group 0970 - 10503 to boroondara/0970 - 10503.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.86735     145.09195  2006-10-01   37   30   26   29   14   20   14
1    -37.86735     145.09195  2006-10-02   10   10    3    5    7    4    2
2    -37.86735     145.09195  2006-10-03    8    5   11    6    5    1    3
3    -37.86735     145.09195  2006-10-04    6   12   12    7    4    2    3
4    -37.86735     145.09195  2006-10-05   10   13   14    9    6    7    4

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...   30   31   35   30   31   12   14   13   13  0970 - 16116
1  ...   45   47   31   28   30   27   18   15    8  0970 - 16116
2  ...   48   53   42   46   36   35   20   18   13  0970 - 16116
3  ...   51   48   44   33   33   36   20   23    8  0970 - 16116
4  ...   60   64   55   47   62   34   25   21   18  0970 - 16116

[5 rows x 100 columns]
Saved Group 0970 - 16116 to boroondara/0970 - 16116.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.86703     145.09159  2006-10-01   86   83   52   58   59   44   31
1    -37.86703     145.09159  2006-10-02   32   28   17   11    7   11    6
2    -37.86703     145.09159  2006-10-03   26   32   21   14   10   12   13
3    -37.86703     145.09159  2006-10-04   32   22   28   13   16    8   14
4    -37.86703     145.09159  2006-10-05   40   39   21   11   16    9   15

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95  Identifier
0  ...   97   97   66   81   50   59   47   29   34  0970 - 249
1  ...  102  107  114   80   60   62   48   44   26  0970 - 249
2  ...  132  114   86   93   90   73   57   29   40  0970 - 249
3  ...  113  132  101  113   90   78   66   52   44  0970 - 249
4  ...  120  116  113   99   91   61   55   49   36  0970 - 249

[5 rows x 100 columns]
Saved Group 0970 - 249 to boroondara/0970 - 249.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.86723     145.09103  2006-10-01   47   42   31   34   40   28   27
1    -37.86723     145.09103  2006-10-02   15    7    7    7   11    6    4
2    -37.86723     145.09103  2006-10-03   10    8   10    8   10    9    5
3    -37.86723     145.09103  2006-10-05   20   21   13    5    9    7    4
4    -37.86723     145.09103  2006-10-06   16   25   13   15    6    9   14

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95   Identifier
0  ...   48   42   33   34   34   25   22   22   23  0970 - 5887
1  ...   77   58   44   36   28   33   21   25    9  0970 - 5887
2  ...   65   78   50   52   53   38   33   34   22  0970 - 5887
3  ...   74   66   64   67   45   51   47   27   29  0970 - 5887
4  ...   70   54   77   92   61   80   66   52   54  0970 - 5887

[5 rows x 100 columns]
Saved Group 0970 - 5887 to boroondara/0970 - 5887.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.85221     145.09425  2006-10-01  110   93   83   53   58   47   42
1    -37.85221     145.09425  2006-10-02   28   21   21   17   14   10    9
2    -37.85221     145.09425  2006-10-03   23   24   12   11    6    8    6
3    -37.85221     145.09425  2006-10-04   30   32   22   19   18   15   11
4    -37.85221     145.09425  2006-10-05   40   34   25   20   15   23   23

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...  104   95   77   54   54   52   49   40   30  2000 - 10505
1  ...  113  100   89   76   59   55   48   38   26  2000 - 10505
2  ...  153  109   96   90   89   78   60   57   38  2000 - 10505
3  ...  121  125  111   79   85   83   70   46   44  2000 - 10505
4  ...  146  139  112   92  107  103   65   69   50  2000 - 10505

[5 rows x 100 columns]
Saved Group 2000 - 10505 to boroondara/2000 - 10505.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.85193     145.09463  2006-10-01   94   82   49   64   48   50   46
1    -37.85193     145.09463  2006-10-02   46   33   20   11   19    9   13
2    -37.85193     145.09463  2006-10-03   28   28   18   13   14   15   14
3    -37.85193     145.09463  2006-10-04   32   29   25   18   16   11   22
4    -37.85193     145.09463  2006-10-05   34   36   25   32   19   12   16

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...  103   84   88   77   55   51   53   43   47  2000 - 12521
1  ...  121   80   84   79   65   68   48   51   33  2000 - 12521
2  ...  137  134   90   96   76   88   99   35   43  2000 - 12521
3  ...  120  126   99  118   99   91   66   51   40  2000 - 12521
4  ...  121  144  137  111  109   82   71   69   55  2000 - 12521

[5 rows x 100 columns]
Saved Group 2000 - 12521 to boroondara/2000 - 12521.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.85187     145.09407  2006-10-01  115   99   94   86   75   81   81
1    -37.85187     145.09407  2006-10-02   46   43   35   26   33   17   10
2    -37.85187     145.09407  2006-10-03   38   31   29   12   19   31   15
3    -37.85187     145.09407  2006-10-04   43   40   36   20   29   20   20
4    -37.85187     145.09407  2006-10-05   45   37   43   19   32   18   24

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95   Identifier
0  ...  101   97   85  110   79   65   65   56   48  2000 - 2276
1  ...  132  126   95   90   68   64   70   72   49  2000 - 2276
2  ...  146  117  115  123   97   74   64   74   68  2000 - 2276
3  ...  133  132  133  112  101  105   62   84   57  2000 - 2276
4  ...  138  125  137  107  123   90   69   98   71  2000 - 2276

[5 rows x 100 columns]
Saved Group 2000 - 2276 to boroondara/2000 - 2276.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0   -37.851683    145.094346  2006-10-01   46   41   42   36   26   26   19
1   -37.851683    145.094346  2006-10-02   14   14    6    5    5    8    6
2   -37.851683    145.094346  2006-10-03   11   13   11    8   10    4    1
3   -37.851683    145.094346  2006-10-04   16   11   10    7    7    6    4
4   -37.851683    145.094346  2006-10-05   26   14    7    6    7    6   10

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95   Identifier
0  ...   52   63   37   49   34   37   24   14   13  2000 - 6246
1  ...   66   56   66   56   43   45   25   22   17  2000 - 6246
2  ...   82   74   62   54   48   52   28   19   21  2000 - 6246
3  ...   62   86   74   71   38   40   36   46   22  2000 - 6246
4  ...   82   77   75   73   48   38   18   35   12  2000 - 6246

[5 rows x 100 columns]
Saved Group 2000 - 6246 to boroondara/2000 - 6246.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.81631     145.09812  2006-10-01   25   17   16   21   18   10   12
1    -37.81631     145.09812  2006-10-02    4    2    4    6    5    2    0
2    -37.81631     145.09812  2006-10-03    7    7    4    2    7    0    2
3    -37.81631     145.09812  2006-10-04    3    3    2    4    5    2    0
4    -37.81631     145.09812  2006-10-05    8    3    4    5    2    4    3

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...   30   34   28   28   14   14   15   12    5  2200 - 10074
1  ...   24   32   25   21   22   17    7    8    7  2200 - 10074
2  ...   31   40   33   32   46   11   11   11    7  2200 - 10074
3  ...   41   40   26   34   24   25   15    8    8  2200 - 10074
4  ...   35   38   47   31   26   22   15   14    9  2200 - 10074

[5 rows x 100 columns]
Saved Group 2200 - 10074 to boroondara/2200 - 10074.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.81655     145.09831  2006-10-01   38   49   32   24   20   19   20
1    -37.81655     145.09831  2006-10-02   17    6    8    6    6    8    4
2    -37.81655     145.09831  2006-10-03    9    7   10    6    8    9    2
3    -37.81655     145.09831  2006-10-04   16   12   10    8    5    6    7
4    -37.81655     145.09831  2006-10-05   17   12    7    7   11    5    7

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...   46   38   30   21   28   30   28   17   17  2200 - 12428
1  ...   51   62   49   33   24   20   16   15   17  2200 - 12428
2  ...   58   65   49   53   32   34   18   17   15  2200 - 12428
3  ...   48   66   57   28   38   32   28   22   18  2200 - 12428
4  ...   80   63   62   45   34   36   34   19   24  2200 - 12428

[5 rows x 100 columns]
Saved Group 2200 - 12428 to boroondara/2200 - 12428.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.81682     145.09802  2006-10-01   36   30   31   19   27   21   16
1    -37.81682     145.09802  2006-10-02    7    5    4    3    2    4    4
2    -37.81682     145.09802  2006-10-03   10    6    6    5    3    1    2
3    -37.81682     145.09802  2006-10-04   10    8    4   12    6    2    4
4    -37.81682     145.09802  2006-10-05   14   11   11    6    3    2    3

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...   27   33   30   17   20   17   12   15    9  2200 - 20314
1  ...   33   35   33   33   20   15   16   13    6  2200 - 20314
2  ...   41   40   37   34   36   27   29   15   16  2200 - 20314
3  ...   49   35   45   33   36   30   21   21   12  2200 - 20314
4  ...   54   37   45   44   28   37   25   22   14  2200 - 20314

[5 rows x 100 columns]
Saved Group 2200 - 20314 to boroondara/2200 - 20314.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.81648    145.097739  2006-10-01   47   33   36   32   22   25   27
1    -37.81648    145.097739  2006-10-02   19    9    9   14    4    7    5
2    -37.81648    145.097739  2006-10-03   12    8   12    4    8    4    2
3    -37.81648    145.097739  2006-10-04   19   22    9   10    6    2    4
4    -37.81648    145.097739  2006-10-05   20   18   25   18    5   14    6

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95   Identifier
0  ...   41   48   37   46   42   29   24   19   20  2200 - 6819
1  ...   55   57   56   49   27   30   36   21   14  2200 - 6819
2  ...   74   93   72   69   45   29   37   27   22  2200 - 6819
3  ...   82   63   78   65   49   65   46   36   13  2200 - 6819
4  ...   91   45   73   57   43   62   39   37   23  2200 - 6819

[5 rows x 100 columns]
Saved Group 2200 - 6819 to boroondara/2200 - 6819.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.79477     145.03077  2006-10-01   30   34   24   22   23   17   15
1    -37.79477     145.03077  2006-10-02    6    5    9    4   10    2    6
2    -37.79477     145.03077  2006-10-03    8    3    5    1    5    4    4
3    -37.79477     145.03077  2006-10-04   10    7   10    5    3    2    6
4    -37.79477     145.03077  2006-10-05   11   14   11   13    7   12    9

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...   36   29   26   33   22   14   15   11   12  2820 - 14985
1  ...   62   41   31   24   20   18   28    6    5  2820 - 14985
2  ...   54   54   41   30   34   37   27   16   13  2820 - 14985
3  ...   55   56   40   36   36   30   22   17   22  2820 - 14985
4  ...   47   47   59   34   37   28   28   18   25  2820 - 14985

[5 rows x 100 columns]
Saved Group 2820 - 14985 to boroondara/2820 - 14985.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0     -37.7948     145.03015  2006-10-01   84   75   73   50   46   43   33
1     -37.7948     145.03015  2006-10-02   28   21   33   16    6   13   11
2     -37.7948     145.03015  2006-10-03   29   17   19   18    6   10    8
3     -37.7948     145.03015  2006-10-04   24   19   13   17   20    8   12
4     -37.7948     145.03015  2006-10-05   38   26   26   24   21   10    8

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...  101   81   72   72   59   33   45   28   29  2820 - 16542
1  ...  113  109   99   78   83   73   48   37   21  2820 - 16542
2  ...  115  141  116   97   81   73   50   49   32  2820 - 16542
3  ...  150  146  114  107   95   63   54   46   43  2820 - 16542
4  ...  152  142  118  106   97   65   56   59   32  2820 - 16542

[5 rows x 100 columns]
Saved Group 2820 - 16542 to boroondara/2820 - 16542.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.78661     145.06202  2006-10-01   61   83   55   46   60   48   35
1    -37.78661     145.06202  2006-10-02   33   31   19   11    8   13   10
2    -37.78661     145.06202  2006-10-03   19   12   20   12    5    7   10
3    -37.78661     145.06202  2006-10-04   19   33   17   19   14    5    9
4    -37.78661     145.06202  2006-10-05   35   31   11   26   16   12   11

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...   94  103   74   52   54   44   44   25   34  2825 - 16628
1  ...   84   94   94   75   49   55   35   35   19  2825 - 16628
2  ...  138  116  107   93   68   52   59   42   40  2825 - 16628
3  ...  124  115  106   96   92   65   56   43   37  2825 - 16628
4  ...  104   96   81   92   87   81   50   61   36  2825 - 16628

[5 rows x 100 columns]
Saved Group 2825 - 16628 to boroondara/2825 - 16628.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.78267     145.07729  2006-10-01   29   29   33   25   17   22   21
1    -37.78267     145.07729  2006-10-02    7    9    7    4    2    4    6
2    -37.78267     145.07729  2006-10-03   12    5    4    1    2    3    5
3    -37.78267     145.07729  2006-10-04    7    8    9    4    8    5    7
4    -37.78267     145.07729  2006-10-05   15   16   10   10    1    6    8

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...   48   39   30   27   22   23   22   16   11  2827 - 10827
1  ...   52   48   43   30   27   23   19   14    6  2827 - 10827
2  ...   60   42   44   47   40   24   22   17   13  2827 - 10827
3  ...   56   50   62   41   41   38   15   11   22  2827 - 10827
4  ...   63   49   48   37   31   31   33   34   22  2827 - 10827

[5 rows x 100 columns]
Saved Group 2827 - 10827 to boroondara/2827 - 10827.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0   -37.782087    145.077826  2006-10-01   72   57   50   43   31   37   34
1   -37.782087    145.077826  2006-10-02   26   21   29    9   12    8   13
2   -37.782087    145.077826  2006-10-03   17   22   16   13    6   10    7
3   -37.782087    145.077826  2006-10-04   26   21   14   16    9   10   16
4   -37.782087    145.077826  2006-10-05   35   25   15    5   17    4    5

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...   88   75   72   54   67   35   32   35   27  2827 - 12834
1  ...   58   63   78   65   48   50   39   31   14  2827 - 12834
2  ...   56   82   72   57   60   48   52   38   34  2827 - 12834
3  ...   87  100   87   65   59   51   35   45   33  2827 - 12834
4  ...   95   76   78   62   56   58   42   39   35  2827 - 12834

[5 rows x 100 columns]
Saved Group 2827 - 12834 to boroondara/2827 - 12834.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.78127     145.07688  2006-10-01   91   97   80   87   63   50   66
1    -37.78127     145.07688  2006-10-02   32   31   23   21   17   20   17
2    -37.78127     145.07688  2006-10-03   34   21   21   16   17   13    9
3    -37.78127     145.07688  2006-10-04   38   34   27   24   20   19   14
4    -37.78127     145.07688  2006-10-05   48   44   29   15   19   12    9

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95   Identifier
0  ...   66   58   42   66   52   54   58   35   40  2827 - 2578
1  ...   95   65   75   73   69   59   44   31   39  2827 - 2578
2  ...  118  101  102  108   64   65   66   62   41  2827 - 2578
3  ...  114  109  116  105  113   96   84   61   58  2827 - 2578
4  ...  112  115  131  107   99   95   83   58   47  2827 - 2578

[5 rows x 100 columns]
Saved Group 2827 - 2578 to boroondara/2827 - 2578.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.78093     145.07733  2006-10-01   97   92   90   57   45   54   35
1    -37.78093     145.07733  2006-10-02   27   29   18   21   21    6   10
2    -37.78093     145.07733  2006-10-03   23   18   25   18   10    8    8
3    -37.78093     145.07733  2006-10-04   39   23   21   23   12    7    8
4    -37.78093     145.07733  2006-10-05   34   20   29   21   14   14   10

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95  Identifier
0  ...  110   93   90   73   64   59   52   40   46  2827 - 588
1  ...   99   99   78   66   56   49   50   25   34  2827 - 588
2  ...  127  115  100   82  102   58   52   49   33  2827 - 588
3  ...  135  124  134  106   79   64   50   51   45  2827 - 588
4  ...  148  143  121  121   64   85   64   60   47  2827 - 588

[5 rows x 100 columns]
Saved Group 2827 - 588 to boroondara/2827 - 588.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.86088     145.05744  2006-10-01    1    2    1    0    0    0    2
1    -37.86088     145.05744  2006-10-02    1    1    0    0    1    0    2
2    -37.86088     145.05744  2006-10-03    2    1    0    0    0    0    0
3    -37.86088     145.05744  2006-10-04    1    0    1    1    0    0    1
4    -37.86088     145.05744  2006-10-05    4    1    1    0    0    0    0

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95  Identifier
0  ...    5    0    1    1    0    7    0    0    2   2846 - -1
1  ...    1    5    6    2    3    2    1    1    3   2846 - -1
2  ...    1    6    5    3    3    5    1    3    0   2846 - -1
3  ...    5    1    1    3    6    2    1    1    1   2846 - -1
4  ...    5   13    2    3    1    3    2    3    2   2846 - -1

[5 rows x 100 columns]
Saved Group 2846 - -1 to boroondara/2846 - -1.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.86152     145.05851  2006-10-01   67   42   42   35   29   28   21
1    -37.86152     145.05851  2006-10-02   18   14   11    7    6    5    8
2    -37.86152     145.05851  2006-10-03   14    8   16    4    7    6    6
3    -37.86152     145.05851  2006-10-04    8   14   15    9    9    7    9
4    -37.86152     145.05851  2006-10-05   10   11    6    8    6    8    6

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...   50   48   42   27   35   19   16   13   25  2846 - 16119
1  ...   44   59   50   32   33   30   17   18   10  2846 - 16119
2  ...   61   66   51   35   30   33   28   19   12  2846 - 16119
3  ...   67   65   55   54   37   34   36   24   20  2846 - 16119
4  ...   74   83   64   57   55   45   17   37   20  2846 - 16119

[5 rows x 100 columns]
Saved Group 2846 - 16119 to boroondara/2846 - 16119.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0   -37.861267    145.058038  2006-10-01   43   33   34   33   24   25   19
1   -37.861267    145.058038  2006-10-02   16    9   14    9    7    4    5
2   -37.861267    145.058038  2006-10-03    9   13   10    7    7    6    6
3   -37.861267    145.058038  2006-10-04   16   15   19    2    9   11    7

Now we transform to the type used by the *other* model

In [11]:
times_dict = {}
vcols = [f"V{str(i).zfill(2)}" for i in range(96)]
for col in vcols:
    i = int(col[1:]) if len(col[1:]) > 0 else 0
    t = i * 15 
    h = t // 60 
    m = t % 60
    times_dict[col] = f"{str(h).zfill(2)}:{str(m).zfill(2)}"
times_dict

{'V00': '00:00',
 'V01': '00:15',
 'V02': '00:30',
 'V03': '00:45',
 'V04': '01:00',
 'V05': '01:15',
 'V06': '01:30',
 'V07': '01:45',
 'V08': '02:00',
 'V09': '02:15',
 'V10': '02:30',
 'V11': '02:45',
 'V12': '03:00',
 'V13': '03:15',
 'V14': '03:30',
 'V15': '03:45',
 'V16': '04:00',
 'V17': '04:15',
 'V18': '04:30',
 'V19': '04:45',
 'V20': '05:00',
 'V21': '05:15',
 'V22': '05:30',
 'V23': '05:45',
 'V24': '06:00',
 'V25': '06:15',
 'V26': '06:30',
 'V27': '06:45',
 'V28': '07:00',
 'V29': '07:15',
 'V30': '07:30',
 'V31': '07:45',
 'V32': '08:00',
 'V33': '08:15',
 'V34': '08:30',
 'V35': '08:45',
 'V36': '09:00',
 'V37': '09:15',
 'V38': '09:30',
 'V39': '09:45',
 'V40': '10:00',
 'V41': '10:15',
 'V42': '10:30',
 'V43': '10:45',
 'V44': '11:00',
 'V45': '11:15',
 'V46': '11:30',
 'V47': '11:45',
 'V48': '12:00',
 'V49': '12:15',
 'V50': '12:30',
 'V51': '12:45',
 'V52': '13:00',
 'V53': '13:15',
 'V54': '13:30',
 'V55': '13:45',
 'V56': '14:00',
 'V57': '14:15',
 'V58': '14:30',
 'V59': '14:45',
 'V60': '15:00',
 'V61': '15:15',
 'V62': '15:30',
 'V63': '15:45',
 'V64': '16:00',
 'V65': '16:15',
 'V66': '16:30',
 'V67': '16:45',
 'V68': '17:00',
 'V69': '17:15',
 'V70': '17:30',
 'V71': '17:45',
 'V72': '18:00',
 'V73': '18:15',
 'V74': '18:30',
 'V75': '18:45',
 'V76': '19:00',
 'V77': '19:15',
 'V78': '19:30',
 'V79': '19:45',
 'V80': '20:00',
 'V81': '20:15',
 'V82': '20:30',
 'V83': '20:45',
 'V84': '21:00',
 'V85': '21:15',
 'V86': '21:30',
 'V87': '21:45',
 'V88': '22:00',
 'V89': '22:15',
 'V90': '22:30',
 'V91': '22:45',
 'V92': '23:00',
 'V93': '23:15',
 'V94': '23:30',
 'V95': '23:45'}

In [12]:
df[vcols].to_numpy(dtype=int)

array([[ 86,  83,  52, ...,  47,  29,  34],
       [ 32,  28,  17, ...,  48,  44,  26],
       [ 26,  32,  21, ...,  57,  29,  40],
       ...,
       [100,  81,  89, ...,  60,  49,  45],
       [ 40,  29,  36, ...,  62,  50,  62],
       [ 36,  30,  24, ...,  63,  51,  54]], shape=(4128, 96))

In [30]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
import numpy as np
from typing import Any, Optional

def xiaochus_pipeline(identifier: str,
                      lags: int = 12,
                      train_ratio: float = 0.8,
                      seed: Optional[int] = None) -> Any:
#tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, MinMaxScaler]:
    df_id = pd.read_csv(f"datasets/boroondara/{identifier}.csv")
    flow = df_id[vcols].to_numpy(dtype=float).flatten()
    flow = np.array(np.nan_to_num(flow))
    cut = int(len(flow) * train_ratio)
    flow_train_raw = flow[:cut]
    flow_test_raw  = flow[cut:]
    
    scaler = MinMaxScaler(feature_range=(0, 1)).fit(flow_train_raw.reshape(-1, 1))

    flow_train = scaler.transform(flow_train_raw.reshape(-1, 1)).reshape(1, -1)[0]
    flow_test  = scaler.transform(flow_test_raw.reshape(-1, 1)).reshape(1, -1)[0]
    print(flow_train.shape)
    print(flow_test.shape)
    
    train_list, test_list = [], []
    for i in range(lags, len(flow_train)):
        train_list.append(flow_train[i - lags: i + 1])
    for i in range(lags, len(flow_test)):
        test_list.append(flow_test[i - lags: i + 1])
        
    train = np.array(train_list)
    test = np.array(test_list)
    print(f"Train:", train)
    print(f"Test:", test)
    print("Train shape:", train.shape)
    print("Test shape:", test.shape)
        
    if seed is not None:
        np.random.default_rng(seed)
        np.random.shuffle(train)
        
    X_train = train[:, :-1]
    y_train = train[:, -1]
    X_test = test[:, :-1]
    y_test = test[:, -1]
    print("Shape of X_train:", X_train.shape)
    print("Shape of X_test:", X_test.shape)
    print("Shape of y_train:", y_train.shape)
    print("Shape of y_test:", y_test.shape)
    
    return X_train, y_train, X_test, y_test, scaler


lag = 12    
X_train, X_test, y_train, y_test, scaler = xiaochus_pipeline("0970 - 249", lags=lag)
# print("Shape of X_train:", X_train.shape)
# print("Shape of X_test:", X_test.shape)
# print("Shape of y_train:", y_train.shape)
# print("Shape of y_test:", y_test.shape)
print(f"X_train = {X_train}")
print(f"y_train = {y_train}")
print(f"X_test = {X_test}")
print(f"y_test = {y_test}")

(2380,)
(596,)
Train: [[0.18930958 0.18262806 0.11358575 ... 0.03340757 0.05122494 0.05345212]
 [0.18262806 0.11358575 0.12694878 ... 0.05122494 0.05345212 0.05345212]
 [0.11358575 0.12694878 0.12917595 ... 0.05345212 0.05345212 0.0311804 ]
 ...
 [0.6481069  0.74387528 0.72160356 ... 0.78841871 0.73496659 0.6636971 ]
 [0.74387528 0.72160356 0.76391982 ... 0.73496659 0.6636971  0.60579065]
 [0.72160356 0.76391982 0.83296214 ... 0.6636971  0.60579065 0.53229399]]
Test: [[0.63697105 0.46547884 0.39198218 ... 0.27394209 0.28285078 0.29175947]
 [0.46547884 0.39198218 0.48552339 ... 0.28285078 0.29175947 0.28062361]
 [0.39198218 0.48552339 0.34521158 ... 0.29175947 0.28062361 0.19153675]
 ...
 [0.35857461 0.31625835 0.30734967 ... 0.17371938 0.155902   0.12026726]
 [0.31625835 0.30734967 0.3674833  ... 0.155902   0.12026726 0.09799555]
 [0.30734967 0.3674833  0.34521158 ... 0.12026726 0.09799555 0.07126949]]
Train shape: (2368, 13)
Test shape: (584, 13)
Shape of X_train: (2368, 12)
Shape of X_test: (584, 12)
Shape of y_train: (2368,)
Shape of y_test: (584,)
X_train = [[0.18930958 0.18262806 0.11358575 ... 0.05122494 0.03340757 0.05122494]
 [0.18262806 0.11358575 0.12694878 ... 0.03340757 0.05122494 0.05345212]
 [0.11358575 0.12694878 0.12917595 ... 0.05122494 0.05345212 0.05345212]
 ...
 [0.6481069  0.74387528 0.72160356 ... 0.73496659 0.78841871 0.73496659]
 [0.74387528 0.72160356 0.76391982 ... 0.78841871 0.73496659 0.6636971 ]
 [0.72160356 0.76391982 0.83296214 ... 0.73496659 0.6636971  0.60579065]]
y_train = [[0.63697105 0.46547884 0.39198218 ... 0.26057906 0.27394209 0.28285078]
 [0.46547884 0.39198218 0.48552339 ... 0.27394209 0.28285078 0.29175947]
 [0.39198218 0.48552339 0.34521158 ... 0.28285078 0.29175947 0.28062361]
 ...
 [0.35857461 0.31625835 0.30734967 ... 0.18485523 0.17371938 0.155902  ]
 [0.31625835 0.30734967 0.3674833  ... 0.17371938 0.155902   0.12026726]
 [0.30734967 0.3674833  0.34521158 ... 0.155902   0.12026726 0.09799555]]
X_test = [0.05345212 0.05345212 0.0311804  ... 0.6636971  0.60579065 0.53229399]
y_test = [ 0.29175947  0.28062361  0.19153675  0.20267261  0.11804009  0.14699332
  0.13363029  0.06904232  0.08685969  0.077951    0.0467706   0.04454343
  0.04008909  0.02449889  0.0311804   0.0311804   0.01336303  0.01781737
  0.00668151  0.01113586  0.00668151  0.00890869  0.01113586  0.02004454
  0.02227171  0.01781737  0.04008909  0.03786192  0.05345212  0.08463252
  0.15144766  0.16258352  0.23608018  0.39420935  0.51447661  0.5701559
  0.6013363   0.79955457  0.83964365  0.77505568  0.96659243  0.77728285
  0.93986637  0.79287305  0.72605791  0.80846325  0.66815145  0.65033408
  0.68151448  0.65478842  0.69487751  0.70378619  0.61469933  0.60356347
  0.74164811  0.6325167   0.62360802  0.68374165  0.66146993  0.59465479
  0.61247216  0.68374165  0.70824053  0.56124722  0.65033408  0.54342984
  0.64142539  0.60801782  0.67706013  0.63474388  0.72383073  0.72605791
  0.83296214  0.71046771  0.78841871  0.72828508  0.844098    0.76837416
  0.77951002  0.97327394  0.74164811  0.76391982  0.67260579  0.56124722
  0.55233853  0.67260579  0.50334076  0.5077951   0.41202673  0.3674833
  0.35412027  0.30957684  0.26726058  0.28953229  0.44988864  0.43652561
  0.29175947  0.26503341  0.24944321  0.18930958  0.14699332  0.16035635
  0.08017817  0.10467706  0.06458797  0.06681514  0.03340757  0.03340757
  0.04231626  0.02672606  0.0467706   0.03340757  0.02004454  0.0311804
  0.02895323  0.00890869  0.02227171  0.0155902   0.03786192  0.01336303
  0.02449889  0.03563474  0.02004454  0.05567929  0.05345212  0.09576837
  0.15144766  0.1403118   0.22048998  0.34075724  0.54565702  0.52561247
  0.64142539  0.75055679  0.79955457  0.81737194  0.92650334  0.86636971
  0.89755011  0.85746102  0.80846325  0.76837416  0.73273942  0.71492205
  0.61247216  0.62360802  0.66146993  0.72605791  0.63919822  0.65033408
  0.65478842  0.65256125  0.68151448  0.6636971   0.6013363   0.6636971
  0.73719376  0.68374165  0.71269488  0.60356347  0.68596882  0.67706013
  0.61469933  0.64142539  0.75946548  0.74832962  0.6636971   0.74387528
  0.72160356  0.86191537  0.70601336  0.78173719  0.74832962  0.83073497
  0.78841871  0.73273942  0.86191537  0.72383073  0.77728285  0.69042316
  0.62360802  0.54565702  0.55233853  0.48552339  0.43652561  0.33407572
  0.28953229  0.32739421  0.29844098  0.28953229  0.30066815  0.29844098
  0.26280624  0.22271715  0.28953229  0.24276169  0.27394209  0.20489978
  0.20712695  0.17594655  0.14699332  0.1247216   0.09576837  0.10244989
  0.07349666  0.0623608   0.05790646  0.03340757  0.06013363  0.05122494
  0.04231626  0.03340757  0.02895323  0.02227171  0.01781737  0.02227171
  0.04899777  0.02895323  0.04899777  0.05122494  0.0467706   0.05567929
  0.09799555  0.09576837  0.06904232  0.15144766  0.1714922   0.16035635
  0.21826281  0.21826281  0.28062361  0.34966592  0.40311804  0.47884187
  0.56570156  0.59242762  0.57238307  0.57906459  0.63474388  0.65256125
  0.70824053  0.75278396  0.78396437  0.78173719  0.82182628  0.77282851
  0.87973274  0.76837416  0.85300668  0.86859688  0.73496659  0.87973274
  0.80846325  0.90200445  0.73051225  0.86191537  0.8752784   0.83518931
  0.74832962  0.72605791  0.67706013  0.67928731  0.65924276  0.71714922
  0.65924276  0.69487751  0.66592428  0.6013363   0.59688196  0.59242762
  0.6013363   0.6325167   0.51224944  0.54788419  0.57683742  0.53452116
  0.48106904  0.52561247  0.49888641  0.3986637   0.40311804  0.40089087
  0.33853007  0.30734967  0.29175947  0.27839644  0.27394209  0.27171492
  0.28953229  0.24276169  0.27616927  0.22494432  0.28953229  0.27171492
  0.27839644  0.21603563  0.20712695  0.22717149  0.22494432  0.18040089
  0.10244989  0.11581292  0.077951   -0.00222717 -0.00222717 -0.00222717
 -0.00222717  0.07349666  0.06904232  0.08240535  0.07572383  0.05345212
  0.06013363  0.05122494  0.06681514  0.03563474  0.06458797  0.06904232
  0.03340757  0.04231626  0.06681514  0.10022272  0.10690423  0.11581292
  0.10690423  0.1247216   0.16258352  0.16481069  0.17817372  0.17371938
  0.19153675  0.26280624  0.26280624  0.32962138  0.39420935  0.5233853
  0.4298441   0.44988864  0.51447661  0.60356347  0.63697105  0.62583519
  0.70155902  0.62138085  0.68374165  0.69710468  0.78619154  0.75501114
  0.67260579  0.76614699  0.71269488  0.70155902  0.65924276  0.73496659
  0.78619154  0.73273942  0.71714922  0.73273942  0.77282851  0.70601336
  0.66146993  0.76837416  0.66815145  0.59020045  0.5701559   0.5545657
  0.59242762  0.51670379  0.55902004  0.59242762  0.47438753  0.45434298
  0.43207127  0.34075724  0.32516704  0.34298441  0.31625835  0.26503341
  0.29175947  0.33407572  0.33853007  0.29175947  0.28507795  0.25389755
  0.21380846  0.23162584  0.18040089  0.14476615  0.15812918  0.08463252
  0.11358575  0.10467706  0.09576837  0.08017817  0.05122494  0.04231626
  0.04008909  0.0311804   0.02449889  0.03340757  0.02672606  0.01781737
  0.02227171  0.01336303  0.00222717  0.01336303  0.0155902   0.02672606
  0.0155902   0.03563474  0.03340757  0.05122494  0.04899777  0.077951
  0.1403118   0.14699332  0.16481069  0.26726058  0.51224944  0.4766147
  0.54342984  0.69265033  0.81069042  0.81291759  0.83296214  0.83296214
  0.85523385  0.83296214  0.88195991  0.71714922  0.59910913  0.65924276
  0.60356347  0.60579065  0.6013363   0.51893096  0.6013363   0.61024499
  0.60801782  0.56347439  0.58129176  0.62360802  0.62583519  0.57906459
  0.55679287  0.53452116  0.68819599  0.62138085  0.70824053  0.57906459
  0.51893096  0.48775056  0.59910913  0.64142539  0.69487751  0.70824053
  0.70378619  0.73942094  0.67260579  0.67037862  0.73496659  0.78841871
  0.79287305  0.83518931  0.70824053  0.5701559   0.57238307  0.5233853
  0.41870824  0.43429844  0.37416481  0.34966592  0.3518931   0.32962138
  0.27839644  0.31180401  0.28953229  0.24053452  0.22939866  0.27616927
  0.26503341  0.16926503  0.16926503  0.15367483  0.13585746  0.09799555
  0.08463252  0.05790646  0.07572383  0.05790646  0.05567929  0.04008909
  0.02004454  0.02672606  0.02004454  0.02227171  0.02895323  0.02227171
  0.01336303  0.0155902   0.01113586  0.02672606  0.02895323  0.00890869
  0.03786192  0.01113586  0.02672606  0.02895323  0.06681514  0.06681514
  0.13808463  0.14922049  0.1714922   0.35634744  0.50111359  0.52783964
  0.54342984  0.75501114  0.80400891  0.72160356  0.85077951  0.87973274
  0.95768374  0.82628062  0.76837416  0.73051225  0.71492205  0.75723831
  0.57683742  0.67483296  0.68819599  0.63028953  0.63474388  0.69042316
  0.60356347  0.56792873  0.63697105  0.57683742  0.57683742  0.6636971
  0.66592428  0.61469933  0.68151448  0.62806236  0.64587973  0.53452116
  0.63028953  0.63028953  0.61024499  0.69265033  0.74610245  0.72605791
  0.81514477  0.88195991  0.69710468  0.78619154  0.73496659  0.69487751
  0.83296214  0.71714922  0.74164811  0.57238307  0.4922049   0.56347439
  0.48997773  0.51893096  0.41648107  0.38752784  0.32516704  0.35857461
  0.31625835  0.30734967  0.3674833   0.34521158  0.28953229  0.27171492
  0.32293987  0.26503341  0.18485523  0.17371938  0.155902    0.12026726
  0.09799555  0.07126949]

Loss Metric: MAPE

In [31]:
def MAPE(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    """Mean Absolute Percentage Error
    Calculate the mape.

    # Arguments
        y_true: List/ndarray, ture data.
        y_pred: List/ndarray, predicted data.
    # Returns
        mape: Double, result data for train.
    """

    y = [x for x in y_true if x > 0]
    y_pred = np.array([y_pred[i] for i in range(len(y_true)) if y_true[i] > 0])

    num: int = len(y_pred)
    sums: float = 0

    for i in range(num):
        tmp = abs(y[i] - y_pred[i]) / y[i]
        sums += tmp

    mape = sums * (100 / num)

    return mape

In [32]:
from model.model import get_cnn, get_gru, get_lstm, get_saes
from train import train_model, train_seas
from keras import Sequential



config: dict[str, Any] = {"batch": 256, "epochs": 600}

non_saes_layers = [lag, 64, 64, 1]
saes_layers = [lag, 400, 400, 400, 1]

models: dict[str, Sequential] = {
	"lstm": get_lstm(non_saes_layers), 
	"gru": get_gru(non_saes_layers),
	"cnn": get_cnn(non_saes_layers),
	"saes": get_saes(saes_layers)
}

def train_pipeline(identifier: str, model: str, lag: int = 12, config: dict[str, Any] = {"batch": 256, "epochs": 600}) -> None:
    X_train, y_train, _, _, _ = xiaochus_pipeline(identifier, lag)
    model = model.strip().lower()
    if model == "saes":
        X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
        m = models["saes"]
        train_seas(m, X_train, y_train, model, config)
    else:
        X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
        m = models[model]
        train_model(m, X_train, y_train, model, config)
    

identifier = "0970 - 249"

train_pipeline(identifier, "lstm", config={"batch": 256, "epochs": 10})

(2380,)
(596,)
Train: [[0.18930958 0.18262806 0.11358575 ... 0.03340757 0.05122494 0.05345212]
 [0.18262806 0.11358575 0.12694878 ... 0.05122494 0.05345212 0.05345212]
 [0.11358575 0.12694878 0.12917595 ... 0.05345212 0.05345212 0.0311804 ]
 ...
 [0.6481069  0.74387528 0.72160356 ... 0.78841871 0.73496659 0.6636971 ]
 [0.74387528 0.72160356 0.76391982 ... 0.73496659 0.6636971  0.60579065]
 [0.72160356 0.76391982 0.83296214 ... 0.6636971  0.60579065 0.53229399]]
Test: [[0.63697105 0.46547884 0.39198218 ... 0.27394209 0.28285078 0.29175947]
 [0.46547884 0.39198218 0.48552339 ... 0.28285078 0.29175947 0.28062361]
 [0.39198218 0.48552339 0.34521158 ... 0.29175947 0.28062361 0.19153675]
 ...
 [0.35857461 0.31625835 0.30734967 ... 0.17371938 0.155902   0.12026726]
 [0.31625835 0.30734967 0.3674833  ... 0.155902   0.12026726 0.09799555]
 [0.30734967 0.3674833  0.34521158 ... 0.12026726 0.09799555 0.07126949]]
Train shape: (2368, 13)
Test shape: (584, 13)
Shape of X_train: (2368, 12)
Shape of X_test: (584, 12)
Shape of y_train: (2368,)
Shape of y_test: (584,)
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 3s 160ms/step - loss: 0.0801 - mape: 1048363.6875 - val_loss: 0.0555 - val_mape: 364.2803
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0512 - mape: 668217.9375 - val_loss: 0.0342 - val_mape: 200.4889
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0362 - mape: 402247.2812 - val_loss: 0.0317 - val_mape: 157.8866
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0341 - mape: 367334.9062 - val_loss: 0.0298 - val_mape: 151.3749
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0319 - mape: 345178.2188 - val_loss: 0.0285 - val_mape: 149.6480
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0300 - mape: 327219.9062 - val_loss: 0.0262 - val_mape: 152.3859
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0280 - mape: 319574.5000 - val_loss: 0.0246 - val_mape: 155.3115
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0260 - mape: 364746.2500 - val_loss: 0.0224 - val_mape: 141.4118
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0229 - mape: 352083.7500 - val_loss: 0.0201 - val_mape: 124.8839
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0204 - mape: 312541.2812 - val_loss: 0.0172 - val_mape: 129.2852
Metrics: Index(['loss', 'mape', 'val_loss', 'val_mape'], dtype='object')

In [ ]:
from keras.saving import load_model
lstm = Sequential(load_model('model/lstm.keras'))
gru = Sequential(load_model('model/gru.keras'))
saes = Sequential(load_model('model/saes.keras'))
cnn = Sequential(load_model("model/cnn.keras"))
print(type(lstm))
print(type(gru))
print(type(saes))
print(type(cnn))

<class 'keras.src.models.sequential.Sequential'>
<class 'keras.src.models.sequential.Sequential'>
<class 'keras.src.models.sequential.Sequential'>
<class 'keras.src.models.sequential.Sequential'>

In [20]:
from glob import glob
len(glob("datasets/boroondara/*.csv"))

137