In [4]:
import pandas as pd
sheets = pd.read_excel("./datasets/Scats Data October 2006.xls", sheet_name=None)
sheets.keys()

dict_keys(['Notes', 'Data', 'Summary Of Data'])

What does the notes have to say?

In [5]:
sheets["Notes"]["Unnamed: 1"].dropna().to_list()

['Request: ',
 'Attached is the 24 hour volume for 40 SCATS sites collected in Boroondara Council',
 'Collection Period: 1st October 2006 to 31st October 2006 (1st October - last Sunday of School holidays)',
 'Data is available every 15minutes for each day collected. Data was validated as per ISD standards for all sites.',
 'On selected days the Data for the following sites was very poor and was removed: ',
 970,
 2000,
 2820,
 3001,
 3002,
 3127,
 3682,
 3685,
 4057,
 4262,
 4263,
 4264,
 4272,
 4812]

In [6]:
removed_days = sheets["Notes"]["Unnamed: 1"].dropna().to_list()[5:]
removed_days = [int(i) for i in removed_days]
removed_days

[970,
 2000,
 2820,
 3001,
 3002,
 3127,
 3682,
 3685,
 4057,
 4262,
 4263,
 4264,
 4272,
 4812]

In [7]:
df_info = sheets["Summary Of Data"].loc[2:]
df_info.columns = df_info.iloc[0]
df_info = df_info[1:]
df_info["SCATS Number"] = df_info["SCATS Number"].ffill()

df_info.dropna(axis=1, inplace=True)
df_info = df_info.convert_dtypes().infer_objects()
df_info.head(15)

2  SCATS Number                         Location  Total
3          0970  HIGH STREET_RD E of WARRIGAL_RD     31
4          0970  HIGH STREET_RD W of WARRIGAL_RD     30
5          0970  WARRIGAL_RD N of HIGH STREET_RD     31
6          0970  WARRIGAL_RD S of HIGH STREET_RD     31
7          2000     BURWOOD_HWY E of WARRIGAL_RD     29
8          2000       TOORAK_RD W of WARRIGAL_RD     29
9          2000       WARRIGAL_RD N of TOORAK_RD     28
10         2000     WARRIGAL_RD S of BURWOOD_HWY     28
11         2200      MAROONDAH_HWY E of UNION_RD     31
12         2200      MAROONDAH_HWY W of UNION_RD     31
13         2200      UNION_RD N of MAROONDAH_HWY     31
14         2200      UNION_RD S of MAROONDAH_HWY     31
15         2820        EARL_ST SE of PRINCESS_ST     31
16         2820    PRINCESS_ST S of CHANDLER_HWY     30
17         2825        BURKE_RD S of EASTERN_FWY     31

Threshold of Days

In [8]:
df_info_filtered = df_info[df_info["Total"].between(7, 31)]
df_info_filtered

2   SCATS Number                         Location  Total
3           0970  HIGH STREET_RD E of WARRIGAL_RD     31
4           0970  HIGH STREET_RD W of WARRIGAL_RD     30
5           0970  WARRIGAL_RD N of HIGH STREET_RD     31
6           0970  WARRIGAL_RD S of HIGH STREET_RD     31
7           2000     BURWOOD_HWY E of WARRIGAL_RD     29
..           ...                              ...    ...
137         4812          SWAN_ST SW of MADDEN_GV     26
138         4821      BURNLEY_ST S OF VICTORIA_ST     31
139         4821      VICTORIA_ST E OF BURNLEY_ST     31
140         4821      VICTORIA_ST W OF BURNLEY_ST     31
141         4821       WALMER_ST N OF VICTORIA_ST     31

[137 rows x 3 columns]

so these are locations with actually reasonable values, so we can filter out the rest of the shitfuckery

In [9]:

# imagine having good formatting
df = sheets["Data"]
df.columns = pd.Series(df.loc[0])
df = df.loc[1:]

# remove added time
df.loc[:, 'Date'] = pd.to_datetime(df['Date']).dt.date
df = df.convert_dtypes()

# filter good locations
df = df.loc[df["Location"].isin(df_info_filtered["Location"])]

# add location identifier: SCARS Number + VicRoads Internal
df.loc[:, "Identifier"] = df["SCATS Number"].astype(str) + " - " + df["HF VicRoads Internal"].astype(str)
df.columns = df.columns.str.strip()


df.head(10)

,SCATS Number,Location,CD_MELWAY,NB_LATITUDE,NB_LONGITUDE,HF VicRoads Internal,VR Internal Stat,VR Internal Loc,NB_TYPE_SURVEY,Date,...,V87,V88,V89,V90,V91,V92,V93,V94,V95,Identifier
1,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-01,...,97,97,66,81,50,59,47,29,34,0970 - 249
2,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-02,...,102,107,114,80,60,62,48,44,26,0970 - 249
3,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-03,...,132,114,86,93,90,73,57,29,40,0970 - 249
4,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-04,...,113,132,101,113,90,78,66,52,44,0970 - 249
5,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-05,...,120,116,113,99,91,61,55,49,36,0970 - 249
6,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-06,...,137,135,136,108,120,115,102,74,78,0970 - 249
7,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-07,...,153,133,109,140,121,123,115,107,127,0970 - 249
8,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-08,...,92,96,82,80,64,64,48,48,43,0970 - 249
9,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-09,...,107,111,98,83,69,57,50,25,36,0970 - 249
10,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2006-10-10,...,131,124,111,112,103,66,50,49,36,0970 - 249

In [10]:
pd.Categorical(df["NB_TYPE_SURVEY"])

[1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1]
Length: 4128
Categories (1, Int64): [1]

In [11]:
test_unique_cols = ["SCATS Number","HF VicRoads Internal","VR Internal Stat","VR Internal Loc","Location"]

for col in test_unique_cols:
    print(pd.Categorical(df.groupby("Identifier")[col].nunique()))

[1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1]
Length: 137
Categories (1, int64): [1]
[1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1]
Length: 137
Categories (1, int64): [1]
[1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1]
Length: 137
Categories (1, int64): [1]
[1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1]
Length: 137
Categories (1, int64): [1]
[1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1]
Length: 137
Categories (1, int64): [1]

Using Identifiers to identify groups. Now, we need to drop irrelevant group info:

- SCATS Number, VicRoads Internal (included in identifier)
- Location (can be accessible via identifier later)
- Latitude and Longtitude (accessible via Location) (wait keeping this is better)
- VR Internal Stat,VR Internal Loc,NB_TYPE_SURVEY (what even are these?)

In [12]:
groups = df.groupby(by="Identifier")
for name, group in groups:
    # print("Name:", name)
    # print("Info:", group.info())
    gr = group.copy()
    gr = gr.drop(columns=["SCATS Number", "HF VicRoads Internal", "Location", "VR Internal Stat", "VR Internal Loc", "NB_TYPE_SURVEY", "CD_MELWAY"])
    gr.reset_index(drop=True, inplace=True)
    print(gr.head(5))
    gr.to_csv(f"datasets/boroondara/{name}.csv")
    print(f"Saved Group {name} to boroondara/{name}.csv")

0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0     -37.8676     145.09146  2006-10-01   92   93   90   55   64   50   47
1     -37.8676     145.09146  2006-10-02   31   19   20   20   12    8   12
2     -37.8676     145.09146  2006-10-03   20   29   16    9    8   13    8
3     -37.8676     145.09146  2006-10-04   32   30   26   13   22   17   13
4     -37.8676     145.09146  2006-10-05   42   37   19   18   12   20   23

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...  117   87   82   55   58   57   51   41   41  0970 - 10503
1  ...  107  107   88   66   54   68   58   49   29  0970 - 10503
2  ...  144  100  100  102   86   85   68   53   37  0970 - 10503
3  ...  114  131   94   84   82   90   76   50   45  0970 - 10503
4  ...  158  127  118   92  105  113   78   64   62  0970 - 10503

[5 rows x 100 columns]
Saved Group 0970 - 10503 to boroondara/0970 - 10503.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.86735     145.09195  2006-10-01   37   30   26   29   14   20   14
1    -37.86735     145.09195  2006-10-02   10   10    3    5    7    4    2
2    -37.86735     145.09195  2006-10-03    8    5   11    6    5    1    3
3    -37.86735     145.09195  2006-10-04    6   12   12    7    4    2    3
4    -37.86735     145.09195  2006-10-05   10   13   14    9    6    7    4

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...   30   31   35   30   31   12   14   13   13  0970 - 16116
1  ...   45   47   31   28   30   27   18   15    8  0970 - 16116
2  ...   48   53   42   46   36   35   20   18   13  0970 - 16116
3  ...   51   48   44   33   33   36   20   23    8  0970 - 16116
4  ...   60   64   55   47   62   34   25   21   18  0970 - 16116

[5 rows x 100 columns]
Saved Group 0970 - 16116 to boroondara/0970 - 16116.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.86703     145.09159  2006-10-01   86   83   52   58   59   44   31
1    -37.86703     145.09159  2006-10-02   32   28   17   11    7   11    6
2    -37.86703     145.09159  2006-10-03   26   32   21   14   10   12   13
3    -37.86703     145.09159  2006-10-04   32   22   28   13   16    8   14
4    -37.86703     145.09159  2006-10-05   40   39   21   11   16    9   15

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95  Identifier
0  ...   97   97   66   81   50   59   47   29   34  0970 - 249
1  ...  102  107  114   80   60   62   48   44   26  0970 - 249
2  ...  132  114   86   93   90   73   57   29   40  0970 - 249
3  ...  113  132  101  113   90   78   66   52   44  0970 - 249
4  ...  120  116  113   99   91   61   55   49   36  0970 - 249

[5 rows x 100 columns]
Saved Group 0970 - 249 to boroondara/0970 - 249.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.86723     145.09103  2006-10-01   47   42   31   34   40   28   27
1    -37.86723     145.09103  2006-10-02   15    7    7    7   11    6    4
2    -37.86723     145.09103  2006-10-03   10    8   10    8   10    9    5
3    -37.86723     145.09103  2006-10-05   20   21   13    5    9    7    4
4    -37.86723     145.09103  2006-10-06   16   25   13   15    6    9   14

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95   Identifier
0  ...   48   42   33   34   34   25   22   22   23  0970 - 5887
1  ...   77   58   44   36   28   33   21   25    9  0970 - 5887
2  ...   65   78   50   52   53   38   33   34   22  0970 - 5887
3  ...   74   66   64   67   45   51   47   27   29  0970 - 5887
4  ...   70   54   77   92   61   80   66   52   54  0970 - 5887

[5 rows x 100 columns]
Saved Group 0970 - 5887 to boroondara/0970 - 5887.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.85221     145.09425  2006-10-01  110   93   83   53   58   47   42
1    -37.85221     145.09425  2006-10-02   28   21   21   17   14   10    9
2    -37.85221     145.09425  2006-10-03   23   24   12   11    6    8    6
3    -37.85221     145.09425  2006-10-04   30   32   22   19   18   15   11
4    -37.85221     145.09425  2006-10-05   40   34   25   20   15   23   23

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...  104   95   77   54   54   52   49   40   30  2000 - 10505
1  ...  113  100   89   76   59   55   48   38   26  2000 - 10505
2  ...  153  109   96   90   89   78   60   57   38  2000 - 10505
3  ...  121  125  111   79   85   83   70   46   44  2000 - 10505
4  ...  146  139  112   92  107  103   65   69   50  2000 - 10505

[5 rows x 100 columns]
Saved Group 2000 - 10505 to boroondara/2000 - 10505.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.85193     145.09463  2006-10-01   94   82   49   64   48   50   46
1    -37.85193     145.09463  2006-10-02   46   33   20   11   19    9   13
2    -37.85193     145.09463  2006-10-03   28   28   18   13   14   15   14
3    -37.85193     145.09463  2006-10-04   32   29   25   18   16   11   22
4    -37.85193     145.09463  2006-10-05   34   36   25   32   19   12   16

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...  103   84   88   77   55   51   53   43   47  2000 - 12521
1  ...  121   80   84   79   65   68   48   51   33  2000 - 12521
2  ...  137  134   90   96   76   88   99   35   43  2000 - 12521
3  ...  120  126   99  118   99   91   66   51   40  2000 - 12521
4  ...  121  144  137  111  109   82   71   69   55  2000 - 12521

[5 rows x 100 columns]
Saved Group 2000 - 12521 to boroondara/2000 - 12521.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.85187     145.09407  2006-10-01  115   99   94   86   75   81   81
1    -37.85187     145.09407  2006-10-02   46   43   35   26   33   17   10
2    -37.85187     145.09407  2006-10-03   38   31   29   12   19   31   15
3    -37.85187     145.09407  2006-10-04   43   40   36   20   29   20   20
4    -37.85187     145.09407  2006-10-05   45   37   43   19   32   18   24

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95   Identifier
0  ...  101   97   85  110   79   65   65   56   48  2000 - 2276
1  ...  132  126   95   90   68   64   70   72   49  2000 - 2276
2  ...  146  117  115  123   97   74   64   74   68  2000 - 2276
3  ...  133  132  133  112  101  105   62   84   57  2000 - 2276
4  ...  138  125  137  107  123   90   69   98   71  2000 - 2276

[5 rows x 100 columns]
Saved Group 2000 - 2276 to boroondara/2000 - 2276.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0   -37.851683    145.094346  2006-10-01   46   41   42   36   26   26   19
1   -37.851683    145.094346  2006-10-02   14   14    6    5    5    8    6
2   -37.851683    145.094346  2006-10-03   11   13   11    8   10    4    1
3   -37.851683    145.094346  2006-10-04   16   11   10    7    7    6    4
4   -37.851683    145.094346  2006-10-05   26   14    7    6    7    6   10

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95   Identifier
0  ...   52   63   37   49   34   37   24   14   13  2000 - 6246
1  ...   66   56   66   56   43   45   25   22   17  2000 - 6246
2  ...   82   74   62   54   48   52   28   19   21  2000 - 6246
3  ...   62   86   74   71   38   40   36   46   22  2000 - 6246
4  ...   82   77   75   73   48   38   18   35   12  2000 - 6246

[5 rows x 100 columns]
Saved Group 2000 - 6246 to boroondara/2000 - 6246.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.81631     145.09812  2006-10-01   25   17   16   21   18   10   12
1    -37.81631     145.09812  2006-10-02    4    2    4    6    5    2    0
2    -37.81631     145.09812  2006-10-03    7    7    4    2    7    0    2
3    -37.81631     145.09812  2006-10-04    3    3    2    4    5    2    0
4    -37.81631     145.09812  2006-10-05    8    3    4    5    2    4    3

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...   30   34   28   28   14   14   15   12    5  2200 - 10074
1  ...   24   32   25   21   22   17    7    8    7  2200 - 10074
2  ...   31   40   33   32   46   11   11   11    7  2200 - 10074
3  ...   41   40   26   34   24   25   15    8    8  2200 - 10074
4  ...   35   38   47   31   26   22   15   14    9  2200 - 10074

[5 rows x 100 columns]
Saved Group 2200 - 10074 to boroondara/2200 - 10074.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.81655     145.09831  2006-10-01   38   49   32   24   20   19   20
1    -37.81655     145.09831  2006-10-02   17    6    8    6    6    8    4
2    -37.81655     145.09831  2006-10-03    9    7   10    6    8    9    2
3    -37.81655     145.09831  2006-10-04   16   12   10    8    5    6    7
4    -37.81655     145.09831  2006-10-05   17   12    7    7   11    5    7

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...   46   38   30   21   28   30   28   17   17  2200 - 12428
1  ...   51   62   49   33   24   20   16   15   17  2200 - 12428
2  ...   58   65   49   53   32   34   18   17   15  2200 - 12428
3  ...   48   66   57   28   38   32   28   22   18  2200 - 12428
4  ...   80   63   62   45   34   36   34   19   24  2200 - 12428

[5 rows x 100 columns]
Saved Group 2200 - 12428 to boroondara/2200 - 12428.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.81682     145.09802  2006-10-01   36   30   31   19   27   21   16
1    -37.81682     145.09802  2006-10-02    7    5    4    3    2    4    4
2    -37.81682     145.09802  2006-10-03   10    6    6    5    3    1    2
3    -37.81682     145.09802  2006-10-04   10    8    4   12    6    2    4
4    -37.81682     145.09802  2006-10-05   14   11   11    6    3    2    3

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...   27   33   30   17   20   17   12   15    9  2200 - 20314
1  ...   33   35   33   33   20   15   16   13    6  2200 - 20314
2  ...   41   40   37   34   36   27   29   15   16  2200 - 20314
3  ...   49   35   45   33   36   30   21   21   12  2200 - 20314
4  ...   54   37   45   44   28   37   25   22   14  2200 - 20314

[5 rows x 100 columns]
Saved Group 2200 - 20314 to boroondara/2200 - 20314.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.81648    145.097739  2006-10-01   47   33   36   32   22   25   27
1    -37.81648    145.097739  2006-10-02   19    9    9   14    4    7    5
2    -37.81648    145.097739  2006-10-03   12    8   12    4    8    4    2
3    -37.81648    145.097739  2006-10-04   19   22    9   10    6    2    4
4    -37.81648    145.097739  2006-10-05   20   18   25   18    5   14    6

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95   Identifier
0  ...   41   48   37   46   42   29   24   19   20  2200 - 6819
1  ...   55   57   56   49   27   30   36   21   14  2200 - 6819
2  ...   74   93   72   69   45   29   37   27   22  2200 - 6819
3  ...   82   63   78   65   49   65   46   36   13  2200 - 6819
4  ...   91   45   73   57   43   62   39   37   23  2200 - 6819

[5 rows x 100 columns]
Saved Group 2200 - 6819 to boroondara/2200 - 6819.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.79477     145.03077  2006-10-01   30   34   24   22   23   17   15
1    -37.79477     145.03077  2006-10-02    6    5    9    4   10    2    6
2    -37.79477     145.03077  2006-10-03    8    3    5    1    5    4    4
3    -37.79477     145.03077  2006-10-04   10    7   10    5    3    2    6
4    -37.79477     145.03077  2006-10-05   11   14   11   13    7   12    9

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...   36   29   26   33   22   14   15   11   12  2820 - 14985
1  ...   62   41   31   24   20   18   28    6    5  2820 - 14985
2  ...   54   54   41   30   34   37   27   16   13  2820 - 14985
3  ...   55   56   40   36   36   30   22   17   22  2820 - 14985
4  ...   47   47   59   34   37   28   28   18   25  2820 - 14985

[5 rows x 100 columns]
Saved Group 2820 - 14985 to boroondara/2820 - 14985.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0     -37.7948     145.03015  2006-10-01   84   75   73   50   46   43   33
1     -37.7948     145.03015  2006-10-02   28   21   33   16    6   13   11
2     -37.7948     145.03015  2006-10-03   29   17   19   18    6   10    8
3     -37.7948     145.03015  2006-10-04   24   19   13   17   20    8   12
4     -37.7948     145.03015  2006-10-05   38   26   26   24   21   10    8

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...  101   81   72   72   59   33   45   28   29  2820 - 16542
1  ...  113  109   99   78   83   73   48   37   21  2820 - 16542
2  ...  115  141  116   97   81   73   50   49   32  2820 - 16542
3  ...  150  146  114  107   95   63   54   46   43  2820 - 16542
4  ...  152  142  118  106   97   65   56   59   32  2820 - 16542

[5 rows x 100 columns]
Saved Group 2820 - 16542 to boroondara/2820 - 16542.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.78661     145.06202  2006-10-01   61   83   55   46   60   48   35
1    -37.78661     145.06202  2006-10-02   33   31   19   11    8   13   10
2    -37.78661     145.06202  2006-10-03   19   12   20   12    5    7   10
3    -37.78661     145.06202  2006-10-04   19   33   17   19   14    5    9
4    -37.78661     145.06202  2006-10-05   35   31   11   26   16   12   11

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...   94  103   74   52   54   44   44   25   34  2825 - 16628
1  ...   84   94   94   75   49   55   35   35   19  2825 - 16628
2  ...  138  116  107   93   68   52   59   42   40  2825 - 16628
3  ...  124  115  106   96   92   65   56   43   37  2825 - 16628
4  ...  104   96   81   92   87   81   50   61   36  2825 - 16628

[5 rows x 100 columns]
Saved Group 2825 - 16628 to boroondara/2825 - 16628.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.78267     145.07729  2006-10-01   29   29   33   25   17   22   21
1    -37.78267     145.07729  2006-10-02    7    9    7    4    2    4    6
2    -37.78267     145.07729  2006-10-03   12    5    4    1    2    3    5
3    -37.78267     145.07729  2006-10-04    7    8    9    4    8    5    7
4    -37.78267     145.07729  2006-10-05   15   16   10   10    1    6    8

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...   48   39   30   27   22   23   22   16   11  2827 - 10827
1  ...   52   48   43   30   27   23   19   14    6  2827 - 10827
2  ...   60   42   44   47   40   24   22   17   13  2827 - 10827
3  ...   56   50   62   41   41   38   15   11   22  2827 - 10827
4  ...   63   49   48   37   31   31   33   34   22  2827 - 10827

[5 rows x 100 columns]
Saved Group 2827 - 10827 to boroondara/2827 - 10827.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0   -37.782087    145.077826  2006-10-01   72   57   50   43   31   37   34
1   -37.782087    145.077826  2006-10-02   26   21   29    9   12    8   13
2   -37.782087    145.077826  2006-10-03   17   22   16   13    6   10    7
3   -37.782087    145.077826  2006-10-04   26   21   14   16    9   10   16
4   -37.782087    145.077826  2006-10-05   35   25   15    5   17    4    5

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...   88   75   72   54   67   35   32   35   27  2827 - 12834
1  ...   58   63   78   65   48   50   39   31   14  2827 - 12834
2  ...   56   82   72   57   60   48   52   38   34  2827 - 12834
3  ...   87  100   87   65   59   51   35   45   33  2827 - 12834
4  ...   95   76   78   62   56   58   42   39   35  2827 - 12834

[5 rows x 100 columns]
Saved Group 2827 - 12834 to boroondara/2827 - 12834.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.78127     145.07688  2006-10-01   91   97   80   87   63   50   66
1    -37.78127     145.07688  2006-10-02   32   31   23   21   17   20   17
2    -37.78127     145.07688  2006-10-03   34   21   21   16   17   13    9
3    -37.78127     145.07688  2006-10-04   38   34   27   24   20   19   14
4    -37.78127     145.07688  2006-10-05   48   44   29   15   19   12    9

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95   Identifier
0  ...   66   58   42   66   52   54   58   35   40  2827 - 2578
1  ...   95   65   75   73   69   59   44   31   39  2827 - 2578
2  ...  118  101  102  108   64   65   66   62   41  2827 - 2578
3  ...  114  109  116  105  113   96   84   61   58  2827 - 2578
4  ...  112  115  131  107   99   95   83   58   47  2827 - 2578

[5 rows x 100 columns]
Saved Group 2827 - 2578 to boroondara/2827 - 2578.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.78093     145.07733  2006-10-01   97   92   90   57   45   54   35
1    -37.78093     145.07733  2006-10-02   27   29   18   21   21    6   10
2    -37.78093     145.07733  2006-10-03   23   18   25   18   10    8    8
3    -37.78093     145.07733  2006-10-04   39   23   21   23   12    7    8
4    -37.78093     145.07733  2006-10-05   34   20   29   21   14   14   10

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95  Identifier
0  ...  110   93   90   73   64   59   52   40   46  2827 - 588
1  ...   99   99   78   66   56   49   50   25   34  2827 - 588
2  ...  127  115  100   82  102   58   52   49   33  2827 - 588
3  ...  135  124  134  106   79   64   50   51   45  2827 - 588
4  ...  148  143  121  121   64   85   64   60   47  2827 - 588

[5 rows x 100 columns]
Saved Group 2827 - 588 to boroondara/2827 - 588.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.86088     145.05744  2006-10-01    1    2    1    0    0    0    2
1    -37.86088     145.05744  2006-10-02    1    1    0    0    1    0    2
2    -37.86088     145.05744  2006-10-03    2    1    0    0    0    0    0
3    -37.86088     145.05744  2006-10-04    1    0    1    1    0    0    1
4    -37.86088     145.05744  2006-10-05    4    1    1    0    0    0    0

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95  Identifier
0  ...    5    0    1    1    0    7    0    0    2   2846 - -1
1  ...    1    5    6    2    3    2    1    1    3   2846 - -1
2  ...    1    6    5    3    3    5    1    3    0   2846 - -1
3  ...    5    1    1    3    6    2    1    1    1   2846 - -1
4  ...    5   13    2    3    1    3    2    3    2   2846 - -1

[5 rows x 100 columns]
Saved Group 2846 - -1 to boroondara/2846 - -1.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0    -37.86152     145.05851  2006-10-01   67   42   42   35   29   28   21
1    -37.86152     145.05851  2006-10-02   18   14   11    7    6    5    8
2    -37.86152     145.05851  2006-10-03   14    8   16    4    7    6    6
3    -37.86152     145.05851  2006-10-04    8   14   15    9    9    7    9
4    -37.86152     145.05851  2006-10-05   10   11    6    8    6    8    6

0  ...  V87  V88  V89  V90  V91  V92  V93  V94  V95    Identifier
0  ...   50   48   42   27   35   19   16   13   25  2846 - 16119
1  ...   44   59   50   32   33   30   17   18   10  2846 - 16119
2  ...   61   66   51   35   30   33   28   19   12  2846 - 16119
3  ...   67   65   55   54   37   34   36   24   20  2846 - 16119
4  ...   74   83   64   57   55   45   17   37   20  2846 - 16119

[5 rows x 100 columns]
Saved Group 2846 - 16119 to boroondara/2846 - 16119.csv
0  NB_LATITUDE  NB_LONGITUDE        Date  V00  V01  V02  V03  V04  V05  V06  \
0   -37.861267    145.058038  2006-10-01   43   33   34   33   24   25   19
1   -37.861267    145.058038  2006-10-02   16    9   14    9    7    4    5
2   -37.861267    145.058038  2006-10-03    9   13   10    7    7    6    6
3   -37.861267    145.058038  2006-10-04   16   15   19    2    9   11    7

Now we transform to the type used by the *other* model

In [13]:
times_dict = {}
vcols = [f"V{str(i).zfill(2)}" for i in range(96)]
for col in vcols:
    i = int(col[1:]) if len(col[1:]) > 0 else 0
    t = i * 15 
    h = t // 60 
    m = t % 60
    times_dict[col] = f"{str(h).zfill(2)}:{str(m).zfill(2)}"
times_dict

{'V00': '00:00',
 'V01': '00:15',
 'V02': '00:30',
 'V03': '00:45',
 'V04': '01:00',
 'V05': '01:15',
 'V06': '01:30',
 'V07': '01:45',
 'V08': '02:00',
 'V09': '02:15',
 'V10': '02:30',
 'V11': '02:45',
 'V12': '03:00',
 'V13': '03:15',
 'V14': '03:30',
 'V15': '03:45',
 'V16': '04:00',
 'V17': '04:15',
 'V18': '04:30',
 'V19': '04:45',
 'V20': '05:00',
 'V21': '05:15',
 'V22': '05:30',
 'V23': '05:45',
 'V24': '06:00',
 'V25': '06:15',
 'V26': '06:30',
 'V27': '06:45',
 'V28': '07:00',
 'V29': '07:15',
 'V30': '07:30',
 'V31': '07:45',
 'V32': '08:00',
 'V33': '08:15',
 'V34': '08:30',
 'V35': '08:45',
 'V36': '09:00',
 'V37': '09:15',
 'V38': '09:30',
 'V39': '09:45',
 'V40': '10:00',
 'V41': '10:15',
 'V42': '10:30',
 'V43': '10:45',
 'V44': '11:00',
 'V45': '11:15',
 'V46': '11:30',
 'V47': '11:45',
 'V48': '12:00',
 'V49': '12:15',
 'V50': '12:30',
 'V51': '12:45',
 'V52': '13:00',
 'V53': '13:15',
 'V54': '13:30',
 'V55': '13:45',
 'V56': '14:00',
 'V57': '14:15',
 'V58': '14:30',
 'V59': '14:45',
 'V60': '15:00',
 'V61': '15:15',
 'V62': '15:30',
 'V63': '15:45',
 'V64': '16:00',
 'V65': '16:15',
 'V66': '16:30',
 'V67': '16:45',
 'V68': '17:00',
 'V69': '17:15',
 'V70': '17:30',
 'V71': '17:45',
 'V72': '18:00',
 'V73': '18:15',
 'V74': '18:30',
 'V75': '18:45',
 'V76': '19:00',
 'V77': '19:15',
 'V78': '19:30',
 'V79': '19:45',
 'V80': '20:00',
 'V81': '20:15',
 'V82': '20:30',
 'V83': '20:45',
 'V84': '21:00',
 'V85': '21:15',
 'V86': '21:30',
 'V87': '21:45',
 'V88': '22:00',
 'V89': '22:15',
 'V90': '22:30',
 'V91': '22:45',
 'V92': '23:00',
 'V93': '23:15',
 'V94': '23:30',
 'V95': '23:45'}

In [14]:
df[vcols].to_numpy(dtype=int)

array([[ 86,  83,  52, ...,  47,  29,  34],
       [ 32,  28,  17, ...,  48,  44,  26],
       [ 26,  32,  21, ...,  57,  29,  40],
       ...,
       [100,  81,  89, ...,  60,  49,  45],
       [ 40,  29,  36, ...,  62,  50,  62],
       [ 36,  30,  24, ...,  63,  51,  54]], shape=(4128, 96))

In [15]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
import numpy as np
from typing import Any
def xiaochus_pipeline(identifier: str, lag: int = 12, seed: int = 42) -> Any:
#tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, MinMaxScaler]:
    df_id = pd.read_csv(f"datasets/boroondara/{identifier}.csv")
    flow = df_id[vcols].to_numpy(dtype=float).flatten().astype(float)
    scaler = MinMaxScaler((0,1))
    flow_scaled = scaler.fit_transform(flow.reshape(-1,1)).flatten()
    cut = int(len(flow_scaled) * 0.8)
    flow_train = flow_scaled[:cut]
    flow_test  = flow_scaled[cut:]
    
    X_list, y_list = [], []
    for i in range(lag, len(flow_scaled)):
        X_list.append(flow_scaled[i - lag : i])
        y_list.append(flow_scaled[i])
        
    X = np.array(X_list)
    y = np.array(y_list)
        
    cut = int(len(X) * 0.8)
    X_train, X_test = X[:cut], X[cut:]
    y_train, y_test = y[:cut], y[cut:]
    # X_train = train[:, :-1]
    # y_train = train[:, -1]
    # X_test = test[:, :-1]
    # y_test = test[:, -1]
    
    return X_train, y_train, X_test, y_test, scaler

lag = 12    
X_train, X_test, y_train, y_test, scaler = xiaochus_pipeline("0970 - 249", lag=lag)
print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)
print(f"X_train = {X_train}")
print(f"y_train = {y_train}")
print(f"X_test = {X_test}")
print(f"y_test = {y_test}")

Shape of X_train: (2371, 12)
Shape of X_test: (2371,)
Shape of y_train: (593, 12)
Shape of y_test: (593,)
X_train = [[0.19111111 0.18444444 0.11555556 ... 0.05333333 0.03555556 0.05333333]
 [0.18444444 0.11555556 0.12888889 ... 0.03555556 0.05333333 0.05555556]
 [0.11555556 0.12888889 0.13111111 ... 0.05333333 0.05555556 0.05555556]
 ...
 [0.76444444 0.83333333 0.60666667 ... 0.66444444 0.60666667 0.53333333]
 [0.83333333 0.60666667 0.75333333 ... 0.60666667 0.53333333 0.63777778]
 [0.60666667 0.75333333 0.73333333 ... 0.53333333 0.63777778 0.46666667]]
y_train = [[0.75333333 0.73333333 0.80888889 ... 0.63777778 0.46666667 0.39333333]
 [0.73333333 0.80888889 0.73555556 ... 0.46666667 0.39333333 0.48666667]
 [0.80888889 0.73555556 0.78888889 ... 0.39333333 0.48666667 0.34666667]
 ...
 [0.36       0.31777778 0.30888889 ... 0.18666667 0.17555556 0.15777778]
 [0.31777778 0.30888889 0.36888889 ... 0.17555556 0.15777778 0.12222222]
 [0.30888889 0.36888889 0.34666667 ... 0.15777778 0.12222222 0.1       ]]
X_test = [0.05555556 0.05555556 0.03333333 ... 0.63777778 0.46666667 0.39333333]
y_test = [0.48666667 0.34666667 0.29333333 0.3        0.30444444 0.29111111
 0.26222222 0.27555556 0.28444444 0.29333333 0.28222222 0.19333333
 0.20444444 0.12       0.14888889 0.13555556 0.07111111 0.08888889
 0.08       0.04888889 0.04666667 0.04222222 0.02666667 0.03333333
 0.03333333 0.01555556 0.02       0.00888889 0.01333333 0.00888889
 0.01111111 0.01333333 0.02222222 0.02444444 0.02       0.04222222
 0.04       0.05555556 0.08666667 0.15333333 0.16444444 0.23777778
 0.39555556 0.51555556 0.57111111 0.60222222 0.8        0.84
 0.77555556 0.96666667 0.77777778 0.94       0.79333333 0.72666667
 0.80888889 0.66888889 0.65111111 0.68222222 0.65555556 0.69555556
 0.70444444 0.61555556 0.60444444 0.74222222 0.63333333 0.62444444
 0.68444444 0.66222222 0.59555556 0.61333333 0.68444444 0.70888889
 0.56222222 0.65111111 0.54444444 0.64222222 0.60888889 0.67777778
 0.63555556 0.72444444 0.72666667 0.83333333 0.71111111 0.78888889
 0.72888889 0.84444444 0.76888889 0.78       0.97333333 0.74222222
 0.76444444 0.67333333 0.56222222 0.55333333 0.67333333 0.50444444
 0.50888889 0.41333333 0.36888889 0.35555556 0.31111111 0.26888889
 0.29111111 0.45111111 0.43777778 0.29333333 0.26666667 0.25111111
 0.19111111 0.14888889 0.16222222 0.08222222 0.10666667 0.06666667
 0.06888889 0.03555556 0.03555556 0.04444444 0.02888889 0.04888889
 0.03555556 0.02222222 0.03333333 0.03111111 0.01111111 0.02444444
 0.01777778 0.04       0.01555556 0.02666667 0.03777778 0.02222222
 0.05777778 0.05555556 0.09777778 0.15333333 0.14222222 0.22222222
 0.34222222 0.54666667 0.52666667 0.64222222 0.75111111 0.8
 0.81777778 0.92666667 0.86666667 0.89777778 0.85777778 0.80888889
 0.76888889 0.73333333 0.71555556 0.61333333 0.62444444 0.66222222
 0.72666667 0.64       0.65111111 0.65555556 0.65333333 0.68222222
 0.66444444 0.60222222 0.66444444 0.73777778 0.68444444 0.71333333
 0.60444444 0.68666667 0.67777778 0.61555556 0.64222222 0.76
 0.74888889 0.66444444 0.74444444 0.72222222 0.86222222 0.70666667
 0.78222222 0.74888889 0.83111111 0.78888889 0.73333333 0.86222222
 0.72444444 0.77777778 0.69111111 0.62444444 0.54666667 0.55333333
 0.48666667 0.43777778 0.33555556 0.29111111 0.32888889 0.3
 0.29111111 0.30222222 0.3        0.26444444 0.22444444 0.29111111
 0.24444444 0.27555556 0.20666667 0.20888889 0.17777778 0.14888889
 0.12666667 0.09777778 0.10444444 0.07555556 0.06444444 0.06
 0.03555556 0.06222222 0.05333333 0.04444444 0.03555556 0.03111111
 0.02444444 0.02       0.02444444 0.05111111 0.03111111 0.05111111
 0.05333333 0.04888889 0.05777778 0.1        0.09777778 0.07111111
 0.15333333 0.17333333 0.16222222 0.22       0.22       0.28222222
 0.35111111 0.40444444 0.48       0.56666667 0.59333333 0.57333333
 0.58       0.63555556 0.65333333 0.70888889 0.75333333 0.78444444
 0.78222222 0.82222222 0.77333333 0.88       0.76888889 0.85333333
 0.86888889 0.73555556 0.88       0.80888889 0.90222222 0.73111111
 0.86222222 0.87555556 0.83555556 0.74888889 0.72666667 0.67777778
 0.68       0.66       0.71777778 0.66       0.69555556 0.66666667
 0.60222222 0.59777778 0.59333333 0.60222222 0.63333333 0.51333333
 0.54888889 0.57777778 0.53555556 0.48222222 0.52666667 0.5
 0.4        0.40444444 0.40222222 0.34       0.30888889 0.29333333
 0.28       0.27555556 0.27333333 0.29111111 0.24444444 0.27777778
 0.22666667 0.29111111 0.27333333 0.28       0.21777778 0.20888889
 0.22888889 0.22666667 0.18222222 0.10444444 0.11777778 0.08
 0.         0.         0.         0.         0.07555556 0.07111111
 0.08444444 0.07777778 0.05555556 0.06222222 0.05333333 0.06888889
 0.03777778 0.06666667 0.07111111 0.03555556 0.04444444 0.06888889
 0.10222222 0.10888889 0.11777778 0.10888889 0.12666667 0.16444444
 0.16666667 0.18       0.17555556 0.19333333 0.26444444 0.26444444
 0.33111111 0.39555556 0.52444444 0.43111111 0.45111111 0.51555556
 0.60444444 0.63777778 0.62666667 0.70222222 0.62222222 0.68444444
 0.69777778 0.78666667 0.75555556 0.67333333 0.76666667 0.71333333
 0.70222222 0.66       0.73555556 0.78666667 0.73333333 0.71777778
 0.73333333 0.77333333 0.70666667 0.66222222 0.76888889 0.66888889
 0.59111111 0.57111111 0.55555556 0.59333333 0.51777778 0.56
 0.59333333 0.47555556 0.45555556 0.43333333 0.34222222 0.32666667
 0.34444444 0.31777778 0.26666667 0.29333333 0.33555556 0.34
 0.29333333 0.28666667 0.25555556 0.21555556 0.23333333 0.18222222
 0.14666667 0.16       0.08666667 0.11555556 0.10666667 0.09777778
 0.08222222 0.05333333 0.04444444 0.04222222 0.03333333 0.02666667
 0.03555556 0.02888889 0.02       0.02444444 0.01555556 0.00444444
 0.01555556 0.01777778 0.02888889 0.01777778 0.03777778 0.03555556
 0.05333333 0.05111111 0.08       0.14222222 0.14888889 0.16666667
 0.26888889 0.51333333 0.47777778 0.54444444 0.69333333 0.81111111
 0.81333333 0.83333333 0.83333333 0.85555556 0.83333333 0.88222222
 0.71777778 0.6        0.66       0.60444444 0.60666667 0.60222222
 0.52       0.60222222 0.61111111 0.60888889 0.56444444 0.58222222
 0.62444444 0.62666667 0.58       0.55777778 0.53555556 0.68888889
 0.62222222 0.70888889 0.58       0.52       0.48888889 0.6
 0.64222222 0.69555556 0.70888889 0.70444444 0.74       0.67333333
 0.67111111 0.73555556 0.78888889 0.79333333 0.83555556 0.70888889
 0.57111111 0.57333333 0.52444444 0.42       0.43555556 0.37555556
 0.35111111 0.35333333 0.33111111 0.28       0.31333333 0.29111111
 0.24222222 0.23111111 0.27777778 0.26666667 0.17111111 0.17111111
 0.15555556 0.13777778 0.1        0.08666667 0.06       0.07777778
 0.06       0.05777778 0.04222222 0.02222222 0.02888889 0.02222222
 0.02444444 0.03111111 0.02444444 0.01555556 0.01777778 0.01333333
 0.02888889 0.03111111 0.01111111 0.04       0.01333333 0.02888889
 0.03111111 0.06888889 0.06888889 0.14       0.15111111 0.17333333
 0.35777778 0.50222222 0.52888889 0.54444444 0.75555556 0.80444444
 0.72222222 0.85111111 0.88       0.95777778 0.82666667 0.76888889
 0.73111111 0.71555556 0.75777778 0.57777778 0.67555556 0.68888889
 0.63111111 0.63555556 0.69111111 0.60444444 0.56888889 0.63777778
 0.57777778 0.57777778 0.66444444 0.66666667 0.61555556 0.68222222
 0.62888889 0.64666667 0.53555556 0.63111111 0.63111111 0.61111111
 0.69333333 0.74666667 0.72666667 0.81555556 0.88222222 0.69777778
 0.78666667 0.73555556 0.69555556 0.83333333 0.71777778 0.74222222
 0.57333333 0.49333333 0.56444444 0.49111111 0.52       0.41777778
 0.38888889 0.32666667 0.36       0.31777778 0.30888889 0.36888889
 0.34666667 0.29111111 0.27333333 0.32444444 0.26666667 0.18666667
 0.17555556 0.15777778 0.12222222 0.1        0.07333333]

In [16]:
from model.model import get_cnn, get_gru, get_lstm
from train import train_model
from keras import Sequential

config: dict[str, Any] = {"batch": 256, "epochs": 600}

non_saes_layers = [lag, 64, 64, 1]

models: dict[str, Sequential] = {
	"lstm": get_lstm(non_saes_layers), 
	"gru": get_gru(non_saes_layers),
	"cnn": get_cnn(non_saes_layers)
}

identifier = "0970 - 249"
X_train, y_train, _, _, _ = xiaochus_pipeline(identifier, lag)

m = "lstm"
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
train_model(models[m], X_train, y_train, m, config)

Epoch 1/600

c:\Users\duc\Documents\TrafficFlowPrediction\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
c:\Users\duc\Documents\TrafficFlowPrediction\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.0804 - mape: 458.4106 - val_loss: 0.0593 - val_mape: 333.1622
Epoch 2/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0549 - mape: 357.2013 - val_loss: 0.0355 - val_mape: 200.8548
Epoch 3/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0355 - mape: 207.5766 - val_loss: 0.0320 - val_mape: 144.5159
Epoch 4/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0333 - mape: 178.2414 - val_loss: 0.0304 - val_mape: 142.3462
Epoch 5/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0312 - mape: 169.7324 - val_loss: 0.0289 - val_mape: 129.0970
Epoch 6/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0297 - mape: 166.2500 - val_loss: 0.0268 - val_mape: 125.6738
Epoch 7/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0274 - mape: 159.4959 - val_loss: 0.0247 - val_mape: 122.6334
Epoch 8/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0251 - mape: 154.2557 - val_loss: 0.0227 - val_mape: 119.6158
Epoch 9/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0226 - mape: 150.5591 - val_loss: 0.0212 - val_mape: 113.7853
Epoch 10/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0199 - mape: 145.4196 - val_loss: 0.0177 - val_mape: 110.9502
Epoch 11/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0169 - mape: 137.1196 - val_loss: 0.0153 - val_mape: 101.9484
Epoch 12/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0151 - mape: 129.5798 - val_loss: 0.0140 - val_mape: 106.5374
Epoch 13/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0130 - mape: 128.6058 - val_loss: 0.0125 - val_mape: 96.6056
Epoch 14/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0131 - mape: 123.7098 - val_loss: 0.0114 - val_mape: 93.6288
Epoch 15/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0108 - mape: 116.5233 - val_loss: 0.0118 - val_mape: 89.2094
Epoch 16/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.0117 - mape: 113.1056 - val_loss: 0.0107 - val_mape: 94.7730
Epoch 17/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 68ms/step - loss: 0.0102 - mape: 109.9810 - val_loss: 0.0104 - val_mape: 81.6272
Epoch 18/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 70ms/step - loss: 0.0106 - mape: 103.0288 - val_loss: 0.0106 - val_mape: 89.6002
Epoch 19/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 75ms/step - loss: 0.0109 - mape: 109.1386 - val_loss: 0.0101 - val_mape: 77.2666
Epoch 20/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 69ms/step - loss: 0.0093 - mape: 98.5170 - val_loss: 0.0098 - val_mape: 80.5464
Epoch 21/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 75ms/step - loss: 0.0094 - mape: 100.0879 - val_loss: 0.0103 - val_mape: 75.0195
Epoch 22/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 61ms/step - loss: 0.0088 - mape: 96.0018 - val_loss: 0.0109 - val_mape: 75.6334
Epoch 23/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0097 - mape: 97.0910 - val_loss: 0.0086 - val_mape: 79.0054
Epoch 24/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0089 - mape: 97.4102 - val_loss: 0.0084 - val_mape: 73.1263
Epoch 25/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0079 - mape: 93.9940 - val_loss: 0.0094 - val_mape: 66.6763
Epoch 26/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0086 - mape: 90.4586 - val_loss: 0.0082 - val_mape: 72.3291
Epoch 27/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0085 - mape: 93.1095 - val_loss: 0.0104 - val_mape: 69.9025
Epoch 28/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0079 - mape: 87.0176 - val_loss: 0.0080 - val_mape: 79.0370
Epoch 29/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0074 - mape: 88.3250 - val_loss: 0.0099 - val_mape: 67.6167
Epoch 30/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0080 - mape: 86.9497 - val_loss: 0.0078 - val_mape: 66.6904
Epoch 31/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0078 - mape: 85.0569 - val_loss: 0.0084 - val_mape: 75.9962
Epoch 32/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0076 - mape: 85.2975 - val_loss: 0.0081 - val_mape: 73.1763
Epoch 33/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0071 - mape: 84.9534 - val_loss: 0.0074 - val_mape: 68.7506
Epoch 34/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0075 - mape: 85.9889 - val_loss: 0.0071 - val_mape: 64.2653
Epoch 35/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0069 - mape: 81.2488 - val_loss: 0.0070 - val_mape: 64.8229
Epoch 36/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0070 - mape: 82.1475 - val_loss: 0.0070 - val_mape: 60.5159
Epoch 37/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0067 - mape: 78.7188 - val_loss: 0.0077 - val_mape: 64.6141
Epoch 38/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0068 - mape: 79.0308 - val_loss: 0.0071 - val_mape: 59.3668
Epoch 39/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0069 - mape: 76.7462 - val_loss: 0.0066 - val_mape: 61.8889
Epoch 40/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0068 - mape: 76.2819 - val_loss: 0.0067 - val_mape: 67.0809
Epoch 41/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0066 - mape: 78.5005 - val_loss: 0.0069 - val_mape: 60.2844
Epoch 42/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0065 - mape: 76.4925 - val_loss: 0.0072 - val_mape: 62.5501
Epoch 43/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0063 - mape: 75.2734 - val_loss: 0.0066 - val_mape: 53.4307
Epoch 44/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0062 - mape: 74.7786 - val_loss: 0.0075 - val_mape: 56.9118
Epoch 45/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0061 - mape: 70.3081 - val_loss: 0.0068 - val_mape: 70.6927
Epoch 46/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0063 - mape: 79.0696 - val_loss: 0.0067 - val_mape: 53.5832
Epoch 47/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0060 - mape: 72.2334 - val_loss: 0.0060 - val_mape: 58.4809
Epoch 48/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0058 - mape: 72.1028 - val_loss: 0.0060 - val_mape: 50.8100
Epoch 49/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0058 - mape: 71.2102 - val_loss: 0.0072 - val_mape: 52.5281
Epoch 50/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0062 - mape: 68.7072 - val_loss: 0.0058 - val_mape: 56.1963
Epoch 51/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0058 - mape: 71.4267 - val_loss: 0.0059 - val_mape: 52.2130
Epoch 52/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0057 - mape: 68.2453 - val_loss: 0.0067 - val_mape: 51.0249
Epoch 53/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0058 - mape: 68.4267 - val_loss: 0.0056 - val_mape: 50.5135
Epoch 54/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0055 - mape: 67.3900 - val_loss: 0.0055 - val_mape: 54.5766
Epoch 55/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0056 - mape: 68.3812 - val_loss: 0.0055 - val_mape: 52.8859
Epoch 56/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0056 - mape: 66.3862 - val_loss: 0.0054 - val_mape: 57.0700
Epoch 57/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0054 - mape: 67.2696 - val_loss: 0.0057 - val_mape: 48.8883
Epoch 58/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0056 - mape: 66.5676 - val_loss: 0.0060 - val_mape: 50.6310
Epoch 59/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0052 - mape: 66.3918 - val_loss: 0.0058 - val_mape: 48.5848
Epoch 60/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0055 - mape: 65.5877 - val_loss: 0.0054 - val_mape: 48.0877
Epoch 61/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0052 - mape: 61.9504 - val_loss: 0.0052 - val_mape: 53.1770
Epoch 62/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0051 - mape: 64.3280 - val_loss: 0.0051 - val_mape: 50.1649
Epoch 63/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0054 - mape: 64.2888 - val_loss: 0.0053 - val_mape: 45.4257
Epoch 64/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0052 - mape: 62.9356 - val_loss: 0.0053 - val_mape: 44.7305
Epoch 65/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.0050 - mape: 59.7054 - val_loss: 0.0055 - val_mape: 50.8401
Epoch 66/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.0051 - mape: 63.1014 - val_loss: 0.0051 - val_mape: 44.7499
Epoch 67/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0050 - mape: 60.4290 - val_loss: 0.0050 - val_mape: 49.0711
Epoch 68/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0048 - mape: 60.9214 - val_loss: 0.0056 - val_mape: 44.0086
Epoch 69/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0051 - mape: 60.3638 - val_loss: 0.0054 - val_mape: 42.3838
Epoch 70/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0050 - mape: 59.0270 - val_loss: 0.0055 - val_mape: 46.3430
Epoch 71/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0049 - mape: 59.9750 - val_loss: 0.0055 - val_mape: 42.9324
Epoch 72/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0048 - mape: 59.1082 - val_loss: 0.0049 - val_mape: 45.5770
Epoch 73/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0047 - mape: 57.6621 - val_loss: 0.0047 - val_mape: 49.8286
Epoch 74/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0047 - mape: 60.8963 - val_loss: 0.0052 - val_mape: 45.1037
Epoch 75/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0049 - mape: 58.1588 - val_loss: 0.0047 - val_mape: 44.3260
Epoch 76/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0049 - mape: 56.5653 - val_loss: 0.0046 - val_mape: 46.3672
Epoch 77/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0047 - mape: 57.3314 - val_loss: 0.0046 - val_mape: 48.7888
Epoch 78/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0047 - mape: 58.0752 - val_loss: 0.0047 - val_mape: 39.8406
Epoch 79/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0048 - mape: 57.9797 - val_loss: 0.0049 - val_mape: 36.4068
Epoch 80/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0047 - mape: 55.0739 - val_loss: 0.0050 - val_mape: 41.7937
Epoch 81/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0046 - mape: 55.0912 - val_loss: 0.0049 - val_mape: 42.7420
Epoch 82/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0045 - mape: 55.7374 - val_loss: 0.0045 - val_mape: 46.4816
Epoch 83/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0044 - mape: 56.3164 - val_loss: 0.0045 - val_mape: 43.1996
Epoch 84/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0045 - mape: 55.2986 - val_loss: 0.0048 - val_mape: 46.6649
Epoch 85/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0045 - mape: 57.0799 - val_loss: 0.0048 - val_mape: 43.0014
Epoch 86/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0047 - mape: 55.2311 - val_loss: 0.0044 - val_mape: 42.4799
Epoch 87/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.0044 - mape: 53.0826 - val_loss: 0.0050 - val_mape: 45.3466
Epoch 88/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0045 - mape: 55.1554 - val_loss: 0.0044 - val_mape: 41.6656
Epoch 89/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0045 - mape: 51.9083 - val_loss: 0.0043 - val_mape: 49.6839
Epoch 90/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0043 - mape: 54.7450 - val_loss: 0.0043 - val_mape: 44.7944
Epoch 91/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0045 - mape: 56.2094 - val_loss: 0.0046 - val_mape: 38.9981
Epoch 92/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0043 - mape: 51.8682 - val_loss: 0.0043 - val_mape: 44.5179
Epoch 93/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0043 - mape: 51.3797 - val_loss: 0.0045 - val_mape: 49.7641
Epoch 94/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0046 - mape: 55.6166 - val_loss: 0.0042 - val_mape: 43.2491
Epoch 95/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0044 - mape: 55.9073 - val_loss: 0.0044 - val_mape: 39.5512
Epoch 96/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0044 - mape: 53.2861 - val_loss: 0.0043 - val_mape: 38.5837
Epoch 97/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0045 - mape: 51.7099 - val_loss: 0.0042 - val_mape: 46.9317
Epoch 98/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0044 - mape: 54.5918 - val_loss: 0.0043 - val_mape: 43.5645
Epoch 99/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0043 - mape: 50.9659 - val_loss: 0.0041 - val_mape: 42.3675
Epoch 100/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0045 - mape: 52.2790 - val_loss: 0.0043 - val_mape: 37.5743
Epoch 101/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0043 - mape: 52.4099 - val_loss: 0.0041 - val_mape: 44.5818
Epoch 102/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0043 - mape: 51.2774 - val_loss: 0.0041 - val_mape: 43.7924
Epoch 103/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0044 - mape: 50.4516 - val_loss: 0.0043 - val_mape: 42.6984
Epoch 104/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0042 - mape: 51.0703 - val_loss: 0.0041 - val_mape: 43.3295
Epoch 105/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0041 - mape: 51.0289 - val_loss: 0.0046 - val_mape: 42.7234
Epoch 106/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0043 - mape: 51.2368 - val_loss: 0.0042 - val_mape: 39.0730
Epoch 107/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0042 - mape: 50.2571 - val_loss: 0.0042 - val_mape: 37.8744
Epoch 108/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0041 - mape: 49.7755 - val_loss: 0.0044 - val_mape: 39.4694
Epoch 109/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0043 - mape: 50.7451 - val_loss: 0.0040 - val_mape: 40.8101
Epoch 110/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0041 - mape: 50.2715 - val_loss: 0.0043 - val_mape: 39.5787
Epoch 111/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0042 - mape: 50.7754 - val_loss: 0.0041 - val_mape: 37.3307
Epoch 112/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0043 - mape: 49.1703 - val_loss: 0.0041 - val_mape: 32.9680
Epoch 113/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0042 - mape: 48.1868 - val_loss: 0.0045 - val_mape: 37.1254
Epoch 114/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.0041 - mape: 49.0843 - val_loss: 0.0045 - val_mape: 36.7144
Epoch 115/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0043 - mape: 50.7463 - val_loss: 0.0041 - val_mape: 34.8284
Epoch 116/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0042 - mape: 48.3733 - val_loss: 0.0043 - val_mape: 36.0293
Epoch 117/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0042 - mape: 50.1942 - val_loss: 0.0040 - val_mape: 36.1668
Epoch 118/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0040 - mape: 46.9630 - val_loss: 0.0041 - val_mape: 41.7968
Epoch 119/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0042 - mape: 48.7014 - val_loss: 0.0042 - val_mape: 39.4690
Epoch 120/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0042 - mape: 48.9994 - val_loss: 0.0040 - val_mape: 37.7514
Epoch 121/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0041 - mape: 48.8137 - val_loss: 0.0040 - val_mape: 38.7897
Epoch 122/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0041 - mape: 47.0073 - val_loss: 0.0039 - val_mape: 41.4047
Epoch 123/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0042 - mape: 48.4705 - val_loss: 0.0040 - val_mape: 33.8676
Epoch 124/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0040 - mape: 45.9244 - val_loss: 0.0040 - val_mape: 38.8673
Epoch 125/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0041 - mape: 49.3479 - val_loss: 0.0041 - val_mape: 33.8754
Epoch 126/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0041 - mape: 48.0767 - val_loss: 0.0040 - val_mape: 37.8910
Epoch 127/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0040 - mape: 47.0371 - val_loss: 0.0040 - val_mape: 34.6246
Epoch 128/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0041 - mape: 47.9540 - val_loss: 0.0039 - val_mape: 36.0887
Epoch 129/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0041 - mape: 48.3440 - val_loss: 0.0040 - val_mape: 38.6999
Epoch 130/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0041 - mape: 47.7338 - val_loss: 0.0040 - val_mape: 33.7692
Epoch 131/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0041 - mape: 47.1999 - val_loss: 0.0040 - val_mape: 38.5154
Epoch 132/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0040 - mape: 47.5301 - val_loss: 0.0039 - val_mape: 37.2582
Epoch 133/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0041 - mape: 47.6703 - val_loss: 0.0042 - val_mape: 33.9555
Epoch 134/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0040 - mape: 46.8797 - val_loss: 0.0044 - val_mape: 37.8165
Epoch 135/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0041 - mape: 47.1411 - val_loss: 0.0042 - val_mape: 32.2343
Epoch 136/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0041 - mape: 45.7596 - val_loss: 0.0039 - val_mape: 38.0144
Epoch 137/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0040 - mape: 45.7723 - val_loss: 0.0039 - val_mape: 36.5089
Epoch 138/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0042 - mape: 47.8435 - val_loss: 0.0039 - val_mape: 34.5839
Epoch 139/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0040 - mape: 48.4278 - val_loss: 0.0042 - val_mape: 31.8525
Epoch 140/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0039 - mape: 45.1165 - val_loss: 0.0041 - val_mape: 34.4760
Epoch 141/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0040 - mape: 46.4552 - val_loss: 0.0041 - val_mape: 30.9236
Epoch 142/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0041 - mape: 44.9785 - val_loss: 0.0039 - val_mape: 39.0313
Epoch 143/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0041 - mape: 47.5481 - val_loss: 0.0039 - val_mape: 36.2154
Epoch 144/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0039 - mape: 45.7069 - val_loss: 0.0040 - val_mape: 29.7365
Epoch 145/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0041 - mape: 45.6038 - val_loss: 0.0039 - val_mape: 35.1834
Epoch 146/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0040 - mape: 46.5960 - val_loss: 0.0041 - val_mape: 37.0621
Epoch 147/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0040 - mape: 45.6956 - val_loss: 0.0039 - val_mape: 31.6955
Epoch 148/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 0.0039 - mape: 42.5036 - val_loss: 0.0040 - val_mape: 36.0539
Epoch 149/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0039 - mape: 45.7946 - val_loss: 0.0039 - val_mape: 31.3089
Epoch 150/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0042 - mape: 45.0035 - val_loss: 0.0040 - val_mape: 33.5898
Epoch 151/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0040 - mape: 43.5129 - val_loss: 0.0041 - val_mape: 33.9224
Epoch 152/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0040 - mape: 43.7556 - val_loss: 0.0042 - val_mape: 36.1743
Epoch 153/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0039 - mape: 44.3864 - val_loss: 0.0039 - val_mape: 34.0383
Epoch 154/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0040 - mape: 45.2843 - val_loss: 0.0039 - val_mape: 35.8008
Epoch 155/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0039 - mape: 44.6139 - val_loss: 0.0045 - val_mape: 37.9036
Epoch 156/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0040 - mape: 46.2162 - val_loss: 0.0038 - val_mape: 35.8655
Epoch 157/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0039 - mape: 42.8671 - val_loss: 0.0038 - val_mape: 39.9839
Epoch 158/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0040 - mape: 45.4307 - val_loss: 0.0041 - val_mape: 34.1692
Epoch 159/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0040 - mape: 45.6240 - val_loss: 0.0038 - val_mape: 32.6523
Epoch 160/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0038 - mape: 44.5773 - val_loss: 0.0042 - val_mape: 31.8500
Epoch 161/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0040 - mape: 44.5207 - val_loss: 0.0043 - val_mape: 33.5318
Epoch 162/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0039 - mape: 43.2969 - val_loss: 0.0040 - val_mape: 35.9740
Epoch 163/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0039 - mape: 44.1689 - val_loss: 0.0041 - val_mape: 30.5314
Epoch 164/600
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0040 - mape: 42.9715 - val_loss: 0.0039 - val_mape: 33.4160
Epoch 165/600